// PORTAL VIEW ACCESS
export const ADMIN_PORTAL_PRIVILEGE = "WEB_MANAGEMENT"

export const WEB_MANAGEMENT_PRIVILEGE = "WEB_MANAGEMENT"
export const TRAVEL_MANAGEMENT_PRIVILEGE = "TRAVEL_MANAGEMENT"
export const WEB_PAGE_MANAGEMENT_PRIVILEGE = "WEB_MANAGEMENT"
export const EMPLOYEE_MANAGEMENT_PRIVILEGE = "EMPLOYEE_MANAGEMENT"
export const HOTEL_MANAGEMENT_PRIVILEGE = "HOTEL_MANAGEMENT"
export const VEHICLE_MANAGEMENT_PRIVILEGE = "VEHICLE_MANAGEMENT"
export const ERP_SYSTEM_PRIVILEGE = "ERP_SYSTEM"

// DESTINATIONS 
export const DESTINATION_PRIVILEGE = "DESTINATION_VIEW"
export const DESTINATION_VIEW_PRIVILEGE = "DESTINATION_VIEW"
export const DESTINATION_CREATE_PRIVILEGE = "DESTINATION_CREATE"
export const DESTINATION_UPDATE_PRIVILEGE = "DESTINATION_UPDATE"
export const DESTINATION_TERMINATE_PRIVILEGE = "DESTINATION_TERMINATE"

// DESTINATION CATEGORIES
export const DESTINATION_CATEGORY_PRIVILEGE = "DESTINATION_VIEW"
export const DESTINATION_CATEGORY_VIEW_PRIVILEGE = "DESTINATION_VIEW"
export const DESTINATION_CATEGORY_CREATE_PRIVILEGE = "DESTINATION_CREATE"
export const DESTINATION_CATEGORY_UPDATE_PRIVILEGE = "DESTINATION_UPDATE"
export const DESTINATION_CATEGORY_TERMINATE_PRIVILEGE = "DESTINATION_TERMINATE"

// TOURS 
export const TOUR_PRIVILEGE = "TOUR_VIEW"
export const TOUR_VIEW_PRIVILEGE = "TOUR_VIEW"
export const TOUR_CREATE_PRIVILEGE = "TOUR_CREATE"
export const TOUR_UPDATE_PRIVILEGE = "TOUR_UPDATE"
export const TOUR_TERMINATE_PRIVILEGE = "TOUR_TERMINATE"

// TOUR TYPES
export const TOUR_CATEGORY_PRIVILEGE = "TOUR_VIEW"
export const TOUR_CATEGORY_VIEW_PRIVILEGE = "TOUR_VIEW"
export const TOUR_CATEGORY_CREATE_PRIVILEGE = "TOUR_CREATE"
export const TOUR_CATEGORY_UPDATE_PRIVILEGE = "TOUR_UPDATE"
export const TOUR_CATEGORY_TERMINATE_PRIVILEGE = "TOUR_TERMINATE"

// TOUR CATEGORY
export const TOUR_TYPE_PRIVILEGE = "TOUR_VIEW"
export const TOUR_TYPE_VIEW_PRIVILEGE = "TOUR_VIEW"
export const TOUR_TYPE_CREATE_PRIVILEGE = "TOUR_CREATE"
export const TOUR_TYPE_UPDATE_PRIVILEGE = "TOUR_UPDATE"
export const TOUR_TYPE_TERMINATE_PRIVILEGE = "TOUR_TERMINATE"

// TOURS SCHEDULES 
export const TOUR_SCHEDULE_PRIVILEGE = "TOUR_SCHEDULE_VIEW"
export const TOUR_SCHEDULE_VIEW_PRIVILEGE = "TOUR_SCHEDULE_VIEW"
export const TOUR_SCHEDULE_CREATE_PRIVILEGE = "TOUR_SCHEDULE_CREATE"
export const TOUR_SCHEDULE_UPDATE_PRIVILEGE = "TOUR_SCHEDULE_UPDATE"
export const TOUR_SCHEDULE_TERMINATE_PRIVILEGE = "TOUR_SCHEDULE_TERMINATE"

// ACTIVITY Category
export const ACTIVITY_CATEGORY_PRIVILEGE = "ACTIVITY_VIEW"
export const ACTIVITY_CATEGORY_VIEW_PRIVILEGE = "ACTIVITY_VIEW"
export const ACTIVITY_CATEGORY_CREATE_PRIVILEGE = "ACTIVITY_CREATE"
export const ACTIVITY_CATEGORY_UPDATE_PRIVILEGE = "ACTIVITY_UPDATE"
export const ACTIVITY_CATEGORY_TERMINATE_PRIVILEGE = "ACTIVITY_TERMINATE"

// ACTIVITIES 
export const ACTIVITY_PRIVILEGE = "ACTIVITY_VIEW"
export const ACTIVITY_VIEW_PRIVILEGE = "ACTIVITY_VIEW"
export const ACTIVITY_CREATE_PRIVILEGE = "ACTIVITY_CREATE"
export const ACTIVITY_UPDATE_PRIVILEGE = "ACTIVITY_UPDATE"
export const ACTIVITY_TERMINATE_PRIVILEGE = "ACTIVITY_TERMINATE"

// ACTIVITIES SCHEDULE
export const ACTIVITY_SCHEDULE_PRIVILEGE = "ACTIVITY_SCHEDULE_VIEW"
export const ACTIVITY_SCHEDULE_VIEW_PRIVILEGE = "ACTIVITY_SCHEDULE_VIEW"
export const ACTIVITY_SCHEDULE_CREATE_PRIVILEGE = "ACTIVITY_SCHEDULE_CREATE"
export const ACTIVITY_SCHEDULE_UPDATE_PRIVILEGE = "ACTIVITY_SCHEDULE_UPDATE"
export const ACTIVITY_SCHEDULE_TERMINATE_PRIVILEGE = "ACTIVITY_SCHEDULE_TERMINATE"

// PACKAGES 
export const PACKAGE_PRIVILEGE = "PACKAGE_VIEW"
export const PACKAGE_VIEW_PRIVILEGE = "PACKAGE_VIEW"
export const PACKAGE_CREATE_PRIVILEGE = "PACKAGE_CREATE"
export const PACKAGE_UPDATE_PRIVILEGE = "PACKAGE_UPDATE"
export const PACKAGE_TERMINATE_PRIVILEGE = "PACKAGE_TERMINATE"

// PACKAGE TYPES
export const PACKAGE_TYPE_PRIVILEGE = "PACKAGE_VIEW"
export const PACKAGE_TYPE_VIEW_PRIVILEGE = "PACKAGE_VIEW"
export const PACKAGE_TYPE_CREATE_PRIVILEGE = "PACKAGE_CREATE"
export const PACKAGE_TYPE_UPDATE_PRIVILEGE = "PACKAGE_UPDATE"
export const PACKAGE_TYPE_TERMINATE_PRIVILEGE = "PACKAGE_TERMINATE"

// PACKAGES 
export const PACKAGE_SCHEDULE_PRIVILEGE = "PACKAGE_SCHEDULE_VIEW"
export const PACKAGE_SCHEDULE_VIEW_PRIVILEGE = "PACKAGE_SCHEDULE_VIEW"
export const PACKAGE_SCHEDULE_CREATE_PRIVILEGE = "PACKAGE_SCHEDULE_CREATE"
export const PACKAGE_SCHEDULE_UPDATE_PRIVILEGE = "PACKAGE_SCHEDULE_UPDATE"
export const PACKAGE_SCHEDULE_TERMINATE_PRIVILEGE = "PACKAGE_SCHEDULE_TERMINATE"

// HOME PAGE
export const HOME_PAGE_PRIVILEGE = "DESTINATION_VIEW";
export const HOME_HERO_SECTION_PRIVILEGE = "DESTINATION_VIEW";
export const HOME_WHY_CHOOSE_US_PRIVILEGE = "DESTINATION_VIEW";
export const HOME_OUR_SERVICES_PRIVILEGE = "DESTINATION_VIEW";
export const HOME_TRENDING_DESTINATIONS_PRIVILEGE = "DESTINATION_VIEW";
export const HOME_ACTIVE_TOURS_PRIVILEGE = "DESTINATION_VIEW";
export const HOME_TOUR_MAP_PRIVILEGE = "DESTINATION_VIEW";
export const HOME_ACTIVITY_CATEGORIES_PRIVILEGE = "DESTINATION_VIEW";
export const HOME_GALLERY_PRIVILEGE = "DESTINATION_VIEW";
export const HOME_CONTACT_FORM_PRIVILEGE = "DESTINATION_VIEW";

export const HOME_PARTNERS_PRIVILEGE = "DESTINATION_VIEW";
export const HOME_POPULAR_DESTINATIONS_PRIVILEGE = "DESTINATION_VIEW";
export const HOME_NEW_DESTINATIONS_PRIVILEGE = "DESTINATION_VIEW";
export const HOME_POPULAR_TOURS_PRIVILEGE = "DESTINATION_VIEW";
export const HOME_ACTIVITIES_PRIVILEGE = "DESTINATION_VIEW";
export const HOME_PACKAGES_PRIVILEGE = "DESTINATION_VIEW";
export const HOME_ACCOMMODATIONS_PRIVILEGE = "DESTINATION_VIEW";
export const HOME_DESTINATION_CATEGORIES_PRIVILEGE = "DESTINATION_VIEW";
export const HOME_USER_LEVELS_PRIVILEGE = "DESTINATION_VIEW";
export const HOME_USER_LEVELS_BENEFITS_PRIVILEGE = "DESTINATION_VIEW";
export const HOME_USER_BENEFITS_PRIVILEGE = "DESTINATION_VIEW";
export const HOME_REVIEWS_PRIVILEGE = "DESTINATION_VIEW";
export const HOME_BLOGS_SUMMARY_PRIVILEGE = "DESTINATION_VIEW";
export const HOME_WORKFLOW_PRIVILEGE = "DESTINATION_VIEW";
export const HOME_PROMOTIONS_PRIVILEGE = "DESTINATION_VIEW";
export const HOME_FAQ_PRIVILEGE = "DESTINATION_VIEW";
export const HOME_INQUIRE_PRIVILEGE = "DESTINATION_VIEW";


// ABOUT US PAGE
export const ABOUT_US_PAGE_PRIVILEGE = "DESTINATION_VIEW";
export const ABOUT_US_HERO_SECTION_PRIVILEGE = "DESTINATION_VIEW";
export const ABOUT_US_OUR_STORY_PRIVILEGE = "DESTINATION_VIEW";
export const ABOUT_US_CEO_SPEECH_PRIVILEGE = "DESTINATION_VIEW";
export const ABOUT_US_WHY_CHOOSE_US_PRIVILEGE = "DESTINATION_VIEW";

export const ABOUT_US_ALL_EMPLOYEES_PRIVILEGE = "DESTINATION_VIEW";
export const ABOUT_US_STATISTICS_PRIVILEGE = "DESTINATION_VIEW";
export const ABOUT_US_EMPLOYEE_SOCIAL_MEDIA_PRIVILEGE = "DESTINATION_VIEW";
export const ABOUT_US_TOUR_GUIDES_PRIVILEGE = "DESTINATION_VIEW";
export const ABOUT_US_OUR_OFFICE_PRIVILEGE = "DESTINATION_VIEW";
export const ABOUT_US_OUR_FEATURES_PRIVILEGE = "DESTINATION_VIEW";
export const ABOUT_US_ACHIEVEMENTS_PRIVILEGE = "DESTINATION_VIEW";


// DESTINATIONS PAGE
export const DESTINATIONS_PAGE_PRIVILEGE = "DESTINATION_VIEW";
export const DESTINATIONS_HERO_SECTION_PRIVILEGE = "DESTINATION_VIEW";
export const DESTINATIONS_REVIEWS_SECTION_PRIVILEGE = "DESTINATION_VIEW";
export const DESTINATIONS_HISTORY_PRIVILEGE = "DESTINATION_VIEW";
export const DESTINATIONS_HISTORY_GALLERY_PRIVILEGE = "DESTINATION_VIEW";


// DESTINATION DETAILS PAGE
export const DESTINATION_DETAILS_PAGE_PRIVILEGE = "DESTINATION_VIEW";
export const DESTINATION_DETAILS_HERO_SECTION_PRIVILEGE = "DESTINATION_VIEW";
export const DESTINATION_DETAILS_HISTORY_PRIVILEGE = "DESTINATION_VIEW";
export const DESTINATION_DETAILS_REVIEWS_SECTION_PRIVILEGE = "DESTINATION_VIEW";
export const DESTINATION_DETAILS_HISTORY_GALLERY_PRIVILEGE = "DESTINATION_VIEW";


// FAQ PAGE
export const FAQ_PAGE_PRIVILEGE = "DESTINATION_VIEW";
export const FAQ_HERO_SECTION_PRIVILEGE = "DESTINATION_VIEW";
export const FAQ_QUESTIONS_ANSWERS_PRIVILEGE = "DESTINATION_VIEW";


// CONTACT US PAGE
export const CONTACT_US_PAGE_PRIVILEGE = "DESTINATION_VIEW";
export const CONTACT_US_HERO_SECTION_PRIVILEGE = "DESTINATION_VIEW";
export const CONTACT_HIGHLIGHTS_PRIVILEGE = "DESTINATION_VIEW";
export const CONTACT_FORM_PRIVILEGE = "DESTINATION_VIEW";
export const CONTACT_CALL_TO_ACTION_PRIVILEGE = "DESTINATION_VIEW";

export const CONTACT_US_OFFICE_PRIVILEGE = "DESTINATION_VIEW";
export const BUSINESS_INFORMATION_PRIVILEGE = "DESTINATION_VIEW";
export const CONTACT_US_SOCIAL_MEDIA_PRIVILEGE = "DESTINATION_VIEW";

// =========================================================
// EMPLOYEE MANAGEMENT PRIVILEGES
// =========================================================
export const EMPLOYEE_PAGE_MANAGEMENT_PRIVILEGE = "EMPLOYEE_MANAGEMENT"
export const EMPLOYEE_VIEW_PRIVILEGE = "DESTINATION_VIEW";
export const EMPLOYEE_CREATE_PRIVILEGE = "DESTINATION_VIEW";
export const EMPLOYEE_UPDATE_PRIVILEGE = "DESTINATION_VIEW";
export const EMPLOYEE_RESIGN_PRIVILEGE = "DESTINATION_VIEW";


// =========================================================
// ROLE MANAGEMENT PRIVILEGES
// =========================================================

export const ROLE_MANAGEMENT_PRIVILEGE = "DESTINATION_VIEW";
export const ROLE_VIEW_PRIVILEGE = "DESTINATION_VIEW";
export const ROLE_CREATE_PRIVILEGE = "DESTINATION_VIEW";
export const ROLE_UPDATE_PRIVILEGE = "DESTINATION_VIEW";
export const ROLE_TERMINATE_PRIVILEGE = "DESTINATION_VIEW";


// =========================================================
// PRIVILEGE MANAGEMENT PRIVILEGES
// =========================================================

export const PRIVILEGE_MANAGEMENT_PRIVILEGE = "DESTINATION_VIEW";
export const PRIVILEGE_VIEW_PRIVILEGE = "DESTINATION_VIEW";
export const PRIVILEGE_CREATE_PRIVILEGE = "DESTINATION_VIEW";
export const PRIVILEGE_UPDATE_PRIVILEGE = "DESTINATION_VIEW";
export const PRIVILEGE_TERMINATE_PRIVILEGE = "DESTINATION_VIEW";