// PORTAL VIEW ACCESS
export const WEB_MANAGEMENT_PRIVILEGE = "WEB_MANAGEMENT"
export const TRAVEL_MANAGEMENT_PRIVILEGE = "TRAVEL_MANAGEMENT"
export const EMPLOYEE_MANAGEMENT_PRIVILEGE = "EMPLOYEE_MANAGEMENT"
export const HOTEL_MANAGEMENT_PRIVILEGE = "HOTEL_MANAGEMENT"
export const VEHICLE_MANAGEMENT_PRIVILEGE = "VEHICLE_MANAGEMENT"
export const ERP_SYSTEM_PRIVILEGE = "ERP_SYSTEM"

// DESTINATIONS 
export const DESTINATION_PRIVILEGE = "DESTINATION_VIEW"
export const DESTINATION_VIEW_PRIVILEGE = "DESTINATION_VIEW"
export const DESTINATION_CREATE_PRIVILEGE = "DESTINATION_CREATE"
export const DESTINATION_UPDATE_PRIVILEGE = "DESTINATION_UPDATE"
export const DESTINATION_TERMINATE_PRIVILEGE = "DESTINATION_TERMINATE"

// TOURS 
export const TOUR_PRIVILEGE = "TOUR_VIEW"
export const TOUR_VIEW_PRIVILEGE = "TOUR_VIEW"
export const TOUR_CREATE_PRIVILEGE = "TOUR_CREATE"
export const TOUR_UPDATE_PRIVILEGE = "TOUR_UPDATE"
export const TOUR_TERMINATE_PRIVILEGE = "TOUR_TERMINATE"

// TOURS SCHEDULES 
export const TOUR_SCHEDULE_PRIVILEGE = "TOUR_SCHEDULE_VIEW"
export const TOUR_SCHEDULE_VIEW_PRIVILEGE = "TOUR_SCHEDULE_VIEW"
export const TOUR_SCHEDULE_CREATE_PRIVILEGE = "TOUR_SCHEDULE_CREATE"
export const TOUR_SCHEDULE_UPDATE_PRIVILEGE = "TOUR_SCHEDULE_UPDATE"
export const TOUR_SCHEDULE_TERMINATE_PRIVILEGE = "TOUR_SCHEDULE_TERMINATE"

// ACTIVITIES 
export const ACTIVITY_PRIVILEGE = "ACTIVITY_VIEW"
export const ACTIVITY_VIEW_PRIVILEGE = "ACTIVITY_VIEW"
export const ACTIVITY_CREATE_PRIVILEGE = "ACTIVITY_CREATE"
export const ACTIVITY_UPDATE_PRIVILEGE = "ACTIVITY_UPDATE"
export const ACTIVITY_TERMINATE_PRIVILEGE = "ACTIVITY_TERMINATE"

// ACTIVITIES SCHEDULE
export const ACTIVITY_SCHEDULE_PRIVILEGE = "ACTIVITY_SCHEDULE_VIEW"
export const ACTIVITY_SCHEDULE_VIEW_PRIVILEGE = "ACTIVITY_SCHEDULE_VIEW"
export const ACTIVITY_SCHEDULE_CREATE_PRIVILEGE = "ACTIVITY_SCHEDULE_CREATE"
export const ACTIVITY_SCHEDULE_UPDATE_PRIVILEGE = "ACTIVITY_SCHEDULE_UPDATE"
export const ACTIVITY_SCHEDULE_TERMINATE_PRIVILEGE = "ACTIVITY_SCHEDULE_TERMINATE"

// PACKAGES 
export const PACKAGE_PRIVILEGE = "PACKAGE_VIEW"
export const PACKAGE_VIEW_PRIVILEGE = "PACKAGE_VIEW"
export const PACKAGE_CREATE_PRIVILEGE = "PACKAGE_CREATE"
export const PACKAGE_UPDATE_PRIVILEGE = "PACKAGE_UPDATE"
export const PACKAGE_TERMINATE_PRIVILEGE = "PACKAGE_TERMINATE"

// PACKAGES 
export const PACKAGE_SCHEDULE_PRIVILEGE = "PACKAGE_SCHEDULE_VIEW"
export const PACKAGE_SCHEDULE_VIEW_PRIVILEGE = "PACKAGE_SCHEDULE_VIEW"
export const PACKAGE_SCHEDULE_CREATE_PRIVILEGE = "PACKAGE_SCHEDULE_CREATE"
export const PACKAGE_SCHEDULE_UPDATE_PRIVILEGE = "PACKAGE_SCHEDULE_UPDATE"
export const PACKAGE_SCHEDULE_TERMINATE_PRIVILEGE = "PACKAGE_SCHEDULE_TERMINATE"