// =========================================================
// PORTAL VIEW ACCESS
// =========================================================
export const ADMIN_PORTAL_PRIVILEGE = "ADMIN_PORTAL";

export const CONTENT_MANAGEMENT_PRIVILEGE = "CONTENT_MANAGEMENT";
export const BOOKING_MANAGEMENT_PRIVILEGE = "BOOKING_MANAGEMENT";
export const WEBSITE_CONTENT_MANAGEMENT_PRIVILEGE =
  "WEBSITE_CONTENT_MANAGEMENT";
export const EMPLOYEE_MANAGEMENT_PRIVILEGE = "EMPLOYEE_MANAGEMENT";
export const HOTEL_MANAGEMENT_PRIVILEGE = "HOTEL_MANAGEMENT";
export const VEHICLE_MANAGEMENT_PRIVILEGE = "VEHICLE_MANAGEMENT";
export const ERP_SYSTEM_PRIVILEGE = "ERP_SYSTEM";

// =========================================================
// DESTINATIONS
// =========================================================
export const DESTINATION_PRIVILEGE = "DESTINATION";
export const DESTINATION_VIEW_PRIVILEGE = "DESTINATION_VIEW";
export const DESTINATION_DETAILS_VIEW_PRIVILEGE = "DESTINATION_DETAILS_VIEW";
export const DESTINATION_CREATE_PRIVILEGE = "DESTINATION_CREATE";
export const DESTINATION_UPDATE_PRIVILEGE = "DESTINATION_UPDATE";
export const DESTINATION_TERMINATE_PRIVILEGE = "DESTINATION_TERMINATE";

// =========================================================
// DESTINATION CATEGORIES
// =========================================================
export const DESTINATION_CATEGORY_PRIVILEGE = "DESTINATION_CATEGORY";
export const DESTINATION_CATEGORY_VIEW_PRIVILEGE = "DESTINATION_CATEGORY_VIEW";
export const DESTINATION_CATEGORY_DETAILS_VIEW_PRIVILEGE = "DESTINATION_CATEGORY_DETAILS_VIEW"; // add database
export const DESTINATION_CATEGORY_CREATE_PRIVILEGE =
  "DESTINATION_CATEGORY_CREATE";
export const DESTINATION_CATEGORY_UPDATE_PRIVILEGE =
  "DESTINATION_CATEGORY_UPDATE";
export const DESTINATION_CATEGORY_TERMINATE_PRIVILEGE =
  "DESTINATION_CATEGORY_TERMINATE";

// =========================================================
// ACTIVITIES
// =========================================================
export const ACTIVITY_PRIVILEGE = "ACTIVITY";
export const ACTIVITY_VIEW_PRIVILEGE = "ACTIVITY_VIEW";
export const ACTIVITY_DETAILS_VIEW_PRIVILEGE = "ACTIVITY_DETAILS_VIEW";
export const ACTIVITY_CREATE_PRIVILEGE = "ACTIVITY_CREATE";
export const ACTIVITY_UPDATE_PRIVILEGE = "ACTIVITY_UPDATE";
export const ACTIVITY_TERMINATE_PRIVILEGE = "ACTIVITY_TERMINATE";

// =========================================================
// ACTIVITY CATEGORIES
// =========================================================
export const ACTIVITY_CATEGORY_PRIVILEGE = "ACTIVITY_CATEGORY";
export const ACTIVITY_CATEGORY_VIEW_PRIVILEGE = "ACTIVITY_CATEGORY_VIEW";
export const ACTIVITY_CATEGORY_DETAILS_VIEW_PRIVILEGE =
  "ACTIVITY_CATEGORY_DETAILS_VIEW";
export const ACTIVITY_CATEGORY_CREATE_PRIVILEGE = "ACTIVITY_CATEGORY_CREATE";
export const ACTIVITY_CATEGORY_UPDATE_PRIVILEGE = "ACTIVITY_CATEGORY_UPDATE";
export const ACTIVITY_CATEGORY_TERMINATE_PRIVILEGE =
  "ACTIVITY_CATEGORY_TERMINATE";

// =========================================================
// ACTIVITY SCHEDULES
// =========================================================
export const ACTIVITY_SCHEDULE_PRIVILEGE = "ACTIVITY_SCHEDULE";
export const ACTIVITY_SCHEDULE_VIEW_PRIVILEGE = "ACTIVITY_SCHEDULE_VIEW";
export const ACTIVITY_SCHEDULE_DETAILS_VIEW_PRIVILEGE =
  "ACTIVITY_SCHEDULE_DETAILS_VIEW";
export const ACTIVITY_SCHEDULE_CREATE_PRIVILEGE = "ACTIVITY_SCHEDULE_CREATE";
export const ACTIVITY_SCHEDULE_UPDATE_PRIVILEGE = "ACTIVITY_SCHEDULE_UPDATE";
export const ACTIVITY_SCHEDULE_TERMINATE_PRIVILEGE =
  "ACTIVITY_SCHEDULE_TERMINATE";

// =========================================================
// TOURS
// =========================================================
export const TOUR_PRIVILEGE = "TOUR";
export const TOUR_VIEW_PRIVILEGE = "TOUR_VIEW";
export const TOUR_DETAILS_VIEW_PRIVILEGE = "TOUR_DETAILS_VIEW";
export const TOUR_CREATE_PRIVILEGE = "TOUR_CREATE";
export const TOUR_UPDATE_PRIVILEGE = "TOUR_UPDATE";
export const TOUR_TERMINATE_PRIVILEGE = "TOUR_TERMINATE";

// =========================================================
// TOUR CATEGORIES
// =========================================================
export const TOUR_CATEGORY_PRIVILEGE = "TOUR_CATEGORY";
export const TOUR_CATEGORY_VIEW_PRIVILEGE = "TOUR_CATEGORY_VIEW";
export const TOUR_CATEGORY_DETAILS_VIEW_PRIVILEGE =
  "TOUR_CATEGORY_DETAILS_VIEW";
export const TOUR_CATEGORY_CREATE_PRIVILEGE = "TOUR_CATEGORY_CREATE";
export const TOUR_CATEGORY_UPDATE_PRIVILEGE = "TOUR_CATEGORY_UPDATE";
export const TOUR_CATEGORY_TERMINATE_PRIVILEGE = "TOUR_CATEGORY_TERMINATE";

// =========================================================
// TOUR TYPES
// =========================================================
export const TOUR_TYPE_PRIVILEGE = "TOUR_TYPE";
export const TOUR_TYPE_VIEW_PRIVILEGE = "TOUR_TYPE_VIEW";
export const TOUR_TYPE_DETAILS_VIEW_PRIVILEGE = "TOUR_TYPE_DETAILS_VIEW";
export const TOUR_TYPE_CREATE_PRIVILEGE = "TOUR_TYPE_CREATE";
export const TOUR_TYPE_UPDATE_PRIVILEGE = "TOUR_TYPE_UPDATE";
export const TOUR_TYPE_TERMINATE_PRIVILEGE = "TOUR_TYPE_TERMINATE";

// =========================================================
// TOUR SCHEDULES
// =========================================================
export const TOUR_SCHEDULE_PRIVILEGE = "TOUR_SCHEDULE";
export const TOUR_SCHEDULE_VIEW_PRIVILEGE = "TOUR_SCHEDULE_VIEW";
export const TOUR_SCHEDULE_DETAILS_VIEW_PRIVILEGE =
  "TOUR_SCHEDULE_DETAILS_VIEW";
export const TOUR_SCHEDULE_CREATE_PRIVILEGE = "TOUR_SCHEDULE_CREATE";
export const TOUR_SCHEDULE_UPDATE_PRIVILEGE = "TOUR_SCHEDULE_UPDATE";
export const TOUR_SCHEDULE_TERMINATE_PRIVILEGE = "TOUR_SCHEDULE_TERMINATE";

// =========================================================
// PACKAGES
// =========================================================
export const PACKAGE_PRIVILEGE = "PACKAGE";
export const PACKAGE_VIEW_PRIVILEGE = "PACKAGE_VIEW";
export const PACKAGE_DETAILS_VIEW_PRIVILEGE = "PACKAGE_DETAILS_VIEW";
export const PACKAGE_CREATE_PRIVILEGE = "PACKAGE_CREATE";
export const PACKAGE_UPDATE_PRIVILEGE = "PACKAGE_UPDATE";
export const PACKAGE_TERMINATE_PRIVILEGE = "PACKAGE_TERMINATE";

// =========================================================
// PACKAGE TYPES
// =========================================================
export const PACKAGE_TYPE_PRIVILEGE = "PACKAGE_TYPE";
export const PACKAGE_TYPE_VIEW_PRIVILEGE = "PACKAGE_TYPE_VIEW";
export const PACKAGE_TYPE_DETAILS_VIEW_PRIVILEGE = "PACKAGE_TYPE_DETAILS_VIEW";
export const PACKAGE_TYPE_CREATE_PRIVILEGE = "PACKAGE_TYPE_CREATE";
export const PACKAGE_TYPE_UPDATE_PRIVILEGE = "PACKAGE_TYPE_UPDATE";
export const PACKAGE_TYPE_TERMINATE_PRIVILEGE = "PACKAGE_TYPE_TERMINATE";

// =========================================================
// PACKAGE SCHEDULES
// =========================================================
export const PACKAGE_SCHEDULE_PRIVILEGE = "PACKAGE_SCHEDULE";
export const PACKAGE_SCHEDULE_VIEW_PRIVILEGE = "PACKAGE_SCHEDULE_VIEW";
export const PACKAGE_SCHEDULE_DETAILS_VIEW_PRIVILEGE =
  "PACKAGE_SCHEDULE_DETAILS_VIEW";
export const PACKAGE_SCHEDULE_CREATE_PRIVILEGE = "PACKAGE_SCHEDULE_CREATE";
export const PACKAGE_SCHEDULE_UPDATE_PRIVILEGE = "PACKAGE_SCHEDULE_UPDATE";
export const PACKAGE_SCHEDULE_TERMINATE_PRIVILEGE =
  "PACKAGE_SCHEDULE_TERMINATE";

// =========================================================
// SEASONS
// =========================================================
export const SEASON_PRIVILEGE = "SEASON";
export const SEASON_VIEW_PRIVILEGE = "SEASON_VIEW";
export const SEASON_DETAILS_VIEW_PRIVILEGE = "SEASON_DETAILS_VIEW";
export const SEASON_CREATE_PRIVILEGE = "SEASON_CREATE";
export const SEASON_UPDATE_PRIVILEGE = "SEASON_UPDATE";
export const SEASON_TERMINATE_PRIVILEGE = "SEASON_TERMINATE";

// =========================================================
// BOOKING MANAGEMENT PRIVILEGES
// =========================================================
// Tour Bookings
export const TOUR_BOOKING_PRIVILEGE = "TOUR_BOOKING";
export const TOUR_BOOKING_VIEW_PRIVILEGE = "TOUR_BOOKING_VIEW";
export const TOUR_BOOKING_DETAILS_VIEW_PRIVILEGE = "TOUR_BOOKING_DETAILS_VIEW";
export const TOUR_BOOKING_CREATE_PRIVILEGE = "TOUR_BOOKING_CREATE";
export const TOUR_BOOKING_UPDATE_PRIVILEGE = "TOUR_BOOKING_UPDATE";
export const TOUR_BOOKING_CANCEL_PRIVILEGE = "TOUR_BOOKING_CANCEL";

// =========================================================
// WEB PAGE MANAGEMENT - HOME PAGE
// =========================================================
export const HOME_PAGE_PRIVILEGE = "HOME_PAGE";

// Hero Section
export const HOME_HERO_SECTION_PRIVILEGE = "HOME_HERO_SECTION";
export const HOME_HERO_SECTION_VIEW_PRIVILEGE = "HOME_HERO_SECTION_VIEW";
export const HOME_HERO_SECTION_DETAILS_VIEW_PRIVILEGE =
  "HOME_HERO_SECTION_DETAILS_VIEW";
export const HOME_HERO_SECTION_ADD_PRIVILEGE = "HOME_HERO_SECTION_ADD";
export const HOME_HERO_SECTION_UPDATE_PRIVILEGE = "HOME_HERO_SECTION_UPDATE";
export const HOME_HERO_SECTION_TERMINATE_PRIVILEGE =
  "HOME_HERO_SECTION_TERMINATE";

// Why Choose Us
export const HOME_WHY_CHOOSE_US_PRIVILEGE = "HOME_WHY_CHOOSE_US";
export const HOME_WHY_CHOOSE_US_VIEW_PRIVILEGE = "HOME_WHY_CHOOSE_US_VIEW";
export const HOME_WHY_CHOOSE_US_DETAILS_VIEW_PRIVILEGE =
  "HOME_WHY_CHOOSE_US_DETAILS_VIEW";
export const HOME_WHY_CHOOSE_US_ADD_PRIVILEGE = "HOME_WHY_CHOOSE_US_ADD";
export const HOME_WHY_CHOOSE_US_UPDATE_PRIVILEGE = "HOME_WHY_CHOOSE_US_UPDATE";
export const HOME_WHY_CHOOSE_US_TERMINATE_PRIVILEGE =
  "HOME_WHY_CHOOSE_US_TERMINATE";

// Our Services
export const HOME_OUR_SERVICES_PRIVILEGE = "HOME_OUR_SERVICES";
export const HOME_OUR_SERVICES_VIEW_PRIVILEGE = "HOME_OUR_SERVICES_VIEW";
export const HOME_OUR_SERVICES_DETAILS_VIEW_PRIVILEGE =
  "HOME_OUR_SERVICES_DETAILS_VIEW";
export const HOME_OUR_SERVICES_ADD_PRIVILEGE = "HOME_OUR_SERVICES_ADD";
export const HOME_OUR_SERVICES_UPDATE_PRIVILEGE = "HOME_OUR_SERVICES_UPDATE";
export const HOME_OUR_SERVICES_TERMINATE_PRIVILEGE =
  "HOME_OUR_SERVICES_TERMINATE";

// Trending Destinations
export const HOME_TRENDING_DESTINATIONS_PRIVILEGE =
  "HOME_TRENDING_DESTINATIONS";
export const HOME_TRENDING_DESTINATIONS_VIEW_PRIVILEGE =
  "HOME_TRENDING_DESTINATIONS_VIEW";
export const HOME_TRENDING_DESTINATIONS_DETAILS_VIEW_PRIVILEGE =
  "HOME_TRENDING_DESTINATIONS_DETAILS_VIEW";
export const HOME_TRENDING_DESTINATIONS_ADD_PRIVILEGE =
  "HOME_TRENDING_DESTINATIONS_ADD";
export const HOME_TRENDING_DESTINATIONS_UPDATE_PRIVILEGE =
  "HOME_TRENDING_DESTINATIONS_UPDATE";
export const HOME_TRENDING_DESTINATIONS_TERMINATE_PRIVILEGE =
  "HOME_TRENDING_DESTINATIONS_TERMINATE";

// Active Tours
export const HOME_ACTIVE_TOURS_PRIVILEGE = "HOME_ACTIVE_TOURS";
export const HOME_ACTIVE_TOURS_VIEW_PRIVILEGE = "HOME_ACTIVE_TOURS_VIEW";
export const HOME_ACTIVE_TOURS_DETAILS_VIEW_PRIVILEGE =
  "HOME_ACTIVE_TOURS_DETAILS_VIEW";
export const HOME_ACTIVE_TOURS_ADD_PRIVILEGE = "HOME_ACTIVE_TOURS_ADD";
export const HOME_ACTIVE_TOURS_UPDATE_PRIVILEGE = "HOME_ACTIVE_TOURS_UPDATE";
export const HOME_ACTIVE_TOURS_TERMINATE_PRIVILEGE =
  "HOME_ACTIVE_TOURS_TERMINATE";

// Tour Map
export const HOME_TOUR_MAP_PRIVILEGE = "HOME_TOUR_MAP";
export const HOME_TOUR_MAP_VIEW_PRIVILEGE = "HOME_TOUR_MAP_VIEW";
export const HOME_TOUR_MAP_DETAILS_VIEW_PRIVILEGE =
  "HOME_TOUR_MAP_DETAILS_VIEW";
export const HOME_TOUR_MAP_ADD_PRIVILEGE = "HOME_TOUR_MAP_ADD";
export const HOME_TOUR_MAP_UPDATE_PRIVILEGE = "HOME_TOUR_MAP_UPDATE";
export const HOME_TOUR_MAP_TERMINATE_PRIVILEGE = "HOME_TOUR_MAP_TERMINATE";

// Activity Categories
export const HOME_ACTIVITY_CATEGORIES_PRIVILEGE = "HOME_ACTIVITY_CATEGORIES";
export const HOME_ACTIVITY_CATEGORIES_VIEW_PRIVILEGE =
  "HOME_ACTIVITY_CATEGORIES_VIEW";
export const HOME_ACTIVITY_CATEGORIES_DETAILS_VIEW_PRIVILEGE =
  "HOME_ACTIVITY_CATEGORIES_DETAILS_VIEW";
export const HOME_ACTIVITY_CATEGORIES_ADD_PRIVILEGE =
  "HOME_ACTIVITY_CATEGORIES_ADD";
export const HOME_ACTIVITY_CATEGORIES_UPDATE_PRIVILEGE =
  "HOME_ACTIVITY_CATEGORIES_UPDATE";
export const HOME_ACTIVITY_CATEGORIES_TERMINATE_PRIVILEGE =
  "HOME_ACTIVITY_CATEGORIES_TERMINATE";

// Gallery
export const HOME_GALLERY_PRIVILEGE = "HOME_GALLERY";
export const HOME_GALLERY_VIEW_PRIVILEGE = "HOME_GALLERY_VIEW";
export const HOME_GALLERY_DETAILS_VIEW_PRIVILEGE = "HOME_GALLERY_DETAILS_VIEW";
export const HOME_GALLERY_ADD_PRIVILEGE = "HOME_GALLERY_ADD";
export const HOME_GALLERY_UPDATE_PRIVILEGE = "HOME_GALLERY_UPDATE";
export const HOME_GALLERY_TERMINATE_PRIVILEGE = "HOME_GALLERY_TERMINATE";

// Contact Form
export const HOME_CONTACT_FORM_PRIVILEGE = "HOME_CONTACT_FORM";
export const HOME_CONTACT_FORM_VIEW_PRIVILEGE = "HOME_CONTACT_FORM_VIEW";
export const HOME_CONTACT_FORM_DETAILS_VIEW_PRIVILEGE =
  "HOME_CONTACT_FORM_DETAILS_VIEW";
export const HOME_CONTACT_FORM_ADD_PRIVILEGE = "HOME_CONTACT_FORM_ADD";
export const HOME_CONTACT_FORM_UPDATE_PRIVILEGE = "HOME_CONTACT_FORM_UPDATE";
export const HOME_CONTACT_FORM_TERMINATE_PRIVILEGE =
  "HOME_CONTACT_FORM_TERMINATE";

// Partners
export const HOME_PARTNERS_PRIVILEGE = "HOME_PARTNERS";
export const HOME_PARTNERS_VIEW_PRIVILEGE = "HOME_PARTNERS_VIEW";
export const HOME_PARTNERS_DETAILS_VIEW_PRIVILEGE =
  "HOME_PARTNERS_DETAILS_VIEW";
export const HOME_PARTNERS_ADD_PRIVILEGE = "HOME_PARTNERS_ADD";
export const HOME_PARTNERS_UPDATE_PRIVILEGE = "HOME_PARTNERS_UPDATE";
export const HOME_PARTNERS_TERMINATE_PRIVILEGE = "HOME_PARTNERS_TERMINATE";

// Popular Destinations
export const HOME_POPULAR_DESTINATIONS_PRIVILEGE = "HOME_POPULAR_DESTINATIONS";
export const HOME_POPULAR_DESTINATIONS_VIEW_PRIVILEGE =
  "HOME_POPULAR_DESTINATIONS_VIEW";
export const HOME_POPULAR_DESTINATIONS_DETAILS_VIEW_PRIVILEGE =
  "HOME_POPULAR_DESTINATIONS_DETAILS_VIEW";
export const HOME_POPULAR_DESTINATIONS_ADD_PRIVILEGE =
  "HOME_POPULAR_DESTINATIONS_ADD";
export const HOME_POPULAR_DESTINATIONS_UPDATE_PRIVILEGE =
  "HOME_POPULAR_DESTINATIONS_UPDATE";
export const HOME_POPULAR_DESTINATIONS_TERMINATE_PRIVILEGE =
  "HOME_POPULAR_DESTINATIONS_TERMINATE";

// New Destinations
export const HOME_NEW_DESTINATIONS_PRIVILEGE = "HOME_NEW_DESTINATIONS";
export const HOME_NEW_DESTINATIONS_VIEW_PRIVILEGE =
  "HOME_NEW_DESTINATIONS_VIEW";
export const HOME_NEW_DESTINATIONS_DETAILS_VIEW_PRIVILEGE =
  "HOME_NEW_DESTINATIONS_DETAILS_VIEW";
export const HOME_NEW_DESTINATIONS_ADD_PRIVILEGE = "HOME_NEW_DESTINATIONS_ADD";
export const HOME_NEW_DESTINATIONS_UPDATE_PRIVILEGE =
  "HOME_NEW_DESTINATIONS_UPDATE";
export const HOME_NEW_DESTINATIONS_TERMINATE_PRIVILEGE =
  "HOME_NEW_DESTINATIONS_TERMINATE";

// Popular Tours
export const HOME_POPULAR_TOURS_PRIVILEGE = "HOME_POPULAR_TOURS";
export const HOME_POPULAR_TOURS_VIEW_PRIVILEGE = "HOME_POPULAR_TOURS_VIEW";
export const HOME_POPULAR_TOURS_DETAILS_VIEW_PRIVILEGE =
  "HOME_POPULAR_TOURS_DETAILS_VIEW";
export const HOME_POPULAR_TOURS_ADD_PRIVILEGE = "HOME_POPULAR_TOURS_ADD";
export const HOME_POPULAR_TOURS_UPDATE_PRIVILEGE = "HOME_POPULAR_TOURS_UPDATE";
export const HOME_POPULAR_TOURS_TERMINATE_PRIVILEGE =
  "HOME_POPULAR_TOURS_TERMINATE";

// Activities
export const HOME_ACTIVITIES_PRIVILEGE = "HOME_ACTIVITIES";
export const HOME_ACTIVITIES_VIEW_PRIVILEGE = "HOME_ACTIVITIES_VIEW";
export const HOME_ACTIVITIES_DETAILS_VIEW_PRIVILEGE =
  "HOME_ACTIVITIES_DETAILS_VIEW";
export const HOME_ACTIVITIES_ADD_PRIVILEGE = "HOME_ACTIVITIES_ADD";
export const HOME_ACTIVITIES_UPDATE_PRIVILEGE = "HOME_ACTIVITIES_UPDATE";
export const HOME_ACTIVITIES_TERMINATE_PRIVILEGE = "HOME_ACTIVITIES_TERMINATE";

// Packages
export const HOME_PACKAGES_PRIVILEGE = "HOME_PACKAGES";
export const HOME_PACKAGES_VIEW_PRIVILEGE = "HOME_PACKAGES_VIEW";
export const HOME_PACKAGES_DETAILS_VIEW_PRIVILEGE =
  "HOME_PACKAGES_DETAILS_VIEW";
export const HOME_PACKAGES_ADD_PRIVILEGE = "HOME_PACKAGES_ADD";
export const HOME_PACKAGES_UPDATE_PRIVILEGE = "HOME_PACKAGES_UPDATE";
export const HOME_PACKAGES_TERMINATE_PRIVILEGE = "HOME_PACKAGES_TERMINATE";

// Accommodations
export const HOME_ACCOMMODATIONS_PRIVILEGE = "HOME_ACCOMMODATIONS";
export const HOME_ACCOMMODATIONS_VIEW_PRIVILEGE = "HOME_ACCOMMODATIONS_VIEW";
export const HOME_ACCOMMODATIONS_DETAILS_VIEW_PRIVILEGE =
  "HOME_ACCOMMODATIONS_DETAILS_VIEW";
export const HOME_ACCOMMODATIONS_ADD_PRIVILEGE = "HOME_ACCOMMODATIONS_ADD";
export const HOME_ACCOMMODATIONS_UPDATE_PRIVILEGE =
  "HOME_ACCOMMODATIONS_UPDATE";
export const HOME_ACCOMMODATIONS_TERMINATE_PRIVILEGE =
  "HOME_ACCOMMODATIONS_TERMINATE";

// Destination Categories
export const HOME_DESTINATION_CATEGORIES_PRIVILEGE =
  "HOME_DESTINATION_CATEGORIES";
export const HOME_DESTINATION_CATEGORIES_VIEW_PRIVILEGE =
  "HOME_DESTINATION_CATEGORIES_VIEW";
export const HOME_DESTINATION_CATEGORIES_DETAILS_VIEW_PRIVILEGE =
  "HOME_DESTINATION_CATEGORIES_DETAILS_VIEW";
export const HOME_DESTINATION_CATEGORIES_ADD_PRIVILEGE =
  "HOME_DESTINATION_CATEGORIES_ADD";
export const HOME_DESTINATION_CATEGORIES_UPDATE_PRIVILEGE =
  "HOME_DESTINATION_CATEGORIES_UPDATE";
export const HOME_DESTINATION_CATEGORIES_TERMINATE_PRIVILEGE =
  "HOME_DESTINATION_CATEGORIES_TERMINATE";

// User Levels
export const HOME_USER_LEVELS_PRIVILEGE = "HOME_USER_LEVELS";
export const HOME_USER_LEVELS_VIEW_PRIVILEGE = "HOME_USER_LEVELS_VIEW";
export const HOME_USER_LEVELS_DETAILS_VIEW_PRIVILEGE =
  "HOME_USER_LEVELS_DETAILS_VIEW";
export const HOME_USER_LEVELS_ADD_PRIVILEGE = "HOME_USER_LEVELS_ADD";
export const HOME_USER_LEVELS_UPDATE_PRIVILEGE = "HOME_USER_LEVELS_UPDATE";
export const HOME_USER_LEVELS_TERMINATE_PRIVILEGE =
  "HOME_USER_LEVELS_TERMINATE";

// User Levels With Benefits
export const HOME_USER_LEVELS_BENEFITS_PRIVILEGE = "HOME_USER_LEVELS_BENEFITS";
export const HOME_USER_LEVELS_BENEFITS_VIEW_PRIVILEGE =
  "HOME_USER_LEVELS_BENEFITS_VIEW";
export const HOME_USER_LEVELS_BENEFITS_DETAILS_VIEW_PRIVILEGE =
  "HOME_USER_LEVELS_BENEFITS_DETAILS_VIEW";
export const HOME_USER_LEVELS_BENEFITS_ADD_PRIVILEGE =
  "HOME_USER_LEVELS_BENEFITS_ADD";
export const HOME_USER_LEVELS_BENEFITS_UPDATE_PRIVILEGE =
  "HOME_USER_LEVELS_BENEFITS_UPDATE";
export const HOME_USER_LEVELS_BENEFITS_TERMINATE_PRIVILEGE =
  "HOME_USER_LEVELS_BENEFITS_TERMINATE";

// User Benefits
export const HOME_USER_BENEFITS_PRIVILEGE = "HOME_USER_BENEFITS";
export const HOME_USER_BENEFITS_VIEW_PRIVILEGE = "HOME_USER_BENEFITS_VIEW";
export const HOME_USER_BENEFITS_DETAILS_VIEW_PRIVILEGE =
  "HOME_USER_BENEFITS_DETAILS_VIEW";
export const HOME_USER_BENEFITS_ADD_PRIVILEGE = "HOME_USER_BENEFITS_ADD";
export const HOME_USER_BENEFITS_UPDATE_PRIVILEGE = "HOME_USER_BENEFITS_UPDATE";
export const HOME_USER_BENEFITS_TERMINATE_PRIVILEGE =
  "HOME_USER_BENEFITS_TERMINATE";

// Reviews
export const HOME_REVIEWS_PRIVILEGE = "HOME_REVIEWS";
export const HOME_REVIEWS_VIEW_PRIVILEGE = "HOME_REVIEWS_VIEW";
export const HOME_REVIEWS_DETAILS_VIEW_PRIVILEGE = "HOME_REVIEWS_DETAILS_VIEW";
export const HOME_REVIEWS_ADD_PRIVILEGE = "HOME_REVIEWS_ADD";
export const HOME_REVIEWS_UPDATE_PRIVILEGE = "HOME_REVIEWS_UPDATE";
export const HOME_REVIEWS_TERMINATE_PRIVILEGE = "HOME_REVIEWS_TERMINATE";

// Blogs Summary
export const HOME_BLOGS_SUMMARY_PRIVILEGE = "HOME_BLOGS_SUMMARY";
export const HOME_BLOGS_SUMMARY_VIEW_PRIVILEGE = "HOME_BLOGS_SUMMARY_VIEW";
export const HOME_BLOGS_SUMMARY_DETAILS_VIEW_PRIVILEGE =
  "HOME_BLOGS_SUMMARY_DETAILS_VIEW";
export const HOME_BLOGS_SUMMARY_ADD_PRIVILEGE = "HOME_BLOGS_SUMMARY_ADD";
export const HOME_BLOGS_SUMMARY_UPDATE_PRIVILEGE = "HOME_BLOGS_SUMMARY_UPDATE";
export const HOME_BLOGS_SUMMARY_TERMINATE_PRIVILEGE =
  "HOME_BLOGS_SUMMARY_TERMINATE";

// Workflow
export const HOME_WORKFLOW_PRIVILEGE = "HOME_WORKFLOW";
export const HOME_WORKFLOW_VIEW_PRIVILEGE = "HOME_WORKFLOW_VIEW";
export const HOME_WORKFLOW_DETAILS_VIEW_PRIVILEGE =
  "HOME_WORKFLOW_DETAILS_VIEW";
export const HOME_WORKFLOW_ADD_PRIVILEGE = "HOME_WORKFLOW_ADD";
export const HOME_WORKFLOW_UPDATE_PRIVILEGE = "HOME_WORKFLOW_UPDATE";
export const HOME_WORKFLOW_TERMINATE_PRIVILEGE = "HOME_WORKFLOW_TERMINATE";

// Promotions
export const HOME_PROMOTIONS_PRIVILEGE = "HOME_PROMOTIONS";
export const HOME_PROMOTIONS_VIEW_PRIVILEGE = "HOME_PROMOTIONS_VIEW";
export const HOME_PROMOTIONS_DETAILS_VIEW_PRIVILEGE =
  "HOME_PROMOTIONS_DETAILS_VIEW";
export const HOME_PROMOTIONS_ADD_PRIVILEGE = "HOME_PROMOTIONS_ADD";
export const HOME_PROMOTIONS_UPDATE_PRIVILEGE = "HOME_PROMOTIONS_UPDATE";
export const HOME_PROMOTIONS_TERMINATE_PRIVILEGE = "HOME_PROMOTIONS_TERMINATE";

// FAQ
export const HOME_FAQ_PRIVILEGE = "HOME_FAQ";
export const HOME_FAQ_VIEW_PRIVILEGE = "HOME_FAQ_VIEW";
export const HOME_FAQ_DETAILS_VIEW_PRIVILEGE = "HOME_FAQ_DETAILS_VIEW";
export const HOME_FAQ_ADD_PRIVILEGE = "HOME_FAQ_ADD";
export const HOME_FAQ_UPDATE_PRIVILEGE = "HOME_FAQ_UPDATE";
export const HOME_FAQ_TERMINATE_PRIVILEGE = "HOME_FAQ_TERMINATE";

// Inquire
export const HOME_INQUIRE_PRIVILEGE = "HOME_INQUIRE";
export const HOME_INQUIRE_VIEW_PRIVILEGE = "HOME_INQUIRE_VIEW";
export const HOME_INQUIRE_DETAILS_VIEW_PRIVILEGE = "HOME_INQUIRE_DETAILS_VIEW";
export const HOME_INQUIRE_ADD_PRIVILEGE = "HOME_INQUIRE_ADD";
export const HOME_INQUIRE_UPDATE_PRIVILEGE = "HOME_INQUIRE_UPDATE";
export const HOME_INQUIRE_TERMINATE_PRIVILEGE = "HOME_INQUIRE_TERMINATE";

// =========================================================
// WEB PAGE MANAGEMENT - ABOUT US PAGE
// =========================================================
export const ABOUT_US_PAGE_PRIVILEGE = "ABOUT_US_PAGE";

// Hero Section
export const ABOUT_US_HERO_SECTION_PRIVILEGE = "ABOUT_US_HERO_SECTION";
export const ABOUT_US_HERO_SECTION_VIEW_PRIVILEGE =
  "ABOUT_US_HERO_SECTION_VIEW";
export const ABOUT_US_HERO_SECTION_DETAILS_VIEW_PRIVILEGE =
  "ABOUT_US_HERO_SECTION_DETAILS_VIEW";
export const ABOUT_US_HERO_SECTION_ADD_PRIVILEGE = "ABOUT_US_HERO_SECTION_ADD";
export const ABOUT_US_HERO_SECTION_UPDATE_PRIVILEGE =
  "ABOUT_US_HERO_SECTION_UPDATE";
export const ABOUT_US_HERO_SECTION_TERMINATE_PRIVILEGE =
  "ABOUT_US_HERO_SECTION_TERMINATE";

// Our Story
export const ABOUT_US_OUR_STORY_PRIVILEGE = "ABOUT_US_OUR_STORY";
export const ABOUT_US_OUR_STORY_VIEW_PRIVILEGE = "ABOUT_US_OUR_STORY_VIEW";
export const ABOUT_US_OUR_STORY_DETAILS_VIEW_PRIVILEGE =
  "ABOUT_US_OUR_STORY_DETAILS_VIEW";
export const ABOUT_US_OUR_STORY_ADD_PRIVILEGE = "ABOUT_US_OUR_STORY_ADD";
export const ABOUT_US_OUR_STORY_UPDATE_PRIVILEGE = "ABOUT_US_OUR_STORY_UPDATE";
export const ABOUT_US_OUR_STORY_TERMINATE_PRIVILEGE =
  "ABOUT_US_OUR_STORY_TERMINATE";

// CEO Speech
export const ABOUT_US_CEO_SPEECH_PRIVILEGE = "ABOUT_US_CEO_SPEECH";
export const ABOUT_US_CEO_SPEECH_VIEW_PRIVILEGE = "ABOUT_US_CEO_SPEECH_VIEW";
export const ABOUT_US_CEO_SPEECH_DETAILS_VIEW_PRIVILEGE =
  "ABOUT_US_CEO_SPEECH_DETAILS_VIEW";
export const ABOUT_US_CEO_SPEECH_ADD_PRIVILEGE = "ABOUT_US_CEO_SPEECH_ADD";
export const ABOUT_US_CEO_SPEECH_UPDATE_PRIVILEGE =
  "ABOUT_US_CEO_SPEECH_UPDATE";
export const ABOUT_US_CEO_SPEECH_TERMINATE_PRIVILEGE =
  "ABOUT_US_CEO_SPEECH_TERMINATE";

// Why Choose Us
export const ABOUT_US_WHY_CHOOSE_US_PRIVILEGE = "ABOUT_US_WHY_CHOOSE_US";
export const ABOUT_US_WHY_CHOOSE_US_VIEW_PRIVILEGE =
  "ABOUT_US_WHY_CHOOSE_US_VIEW";
export const ABOUT_US_WHY_CHOOSE_US_DETAILS_VIEW_PRIVILEGE =
  "ABOUT_US_WHY_CHOOSE_US_DETAILS_VIEW";
export const ABOUT_US_WHY_CHOOSE_US_ADD_PRIVILEGE =
  "ABOUT_US_WHY_CHOOSE_US_ADD";
export const ABOUT_US_WHY_CHOOSE_US_UPDATE_PRIVILEGE =
  "ABOUT_US_WHY_CHOOSE_US_UPDATE";
export const ABOUT_US_WHY_CHOOSE_US_TERMINATE_PRIVILEGE =
  "ABOUT_US_WHY_CHOOSE_US_TERMINATE";

// All Employees
export const ABOUT_US_ALL_EMPLOYEES_PRIVILEGE = "ABOUT_US_ALL_EMPLOYEES";
export const ABOUT_US_ALL_EMPLOYEES_VIEW_PRIVILEGE =
  "ABOUT_US_ALL_EMPLOYEES_VIEW";
export const ABOUT_US_ALL_EMPLOYEES_DETAILS_VIEW_PRIVILEGE =
  "ABOUT_US_ALL_EMPLOYEES_DETAILS_VIEW";
export const ABOUT_US_ALL_EMPLOYEES_ADD_PRIVILEGE =
  "ABOUT_US_ALL_EMPLOYEES_ADD";
export const ABOUT_US_ALL_EMPLOYEES_UPDATE_PRIVILEGE =
  "ABOUT_US_ALL_EMPLOYEES_UPDATE";
export const ABOUT_US_ALL_EMPLOYEES_TERMINATE_PRIVILEGE =
  "ABOUT_US_ALL_EMPLOYEES_TERMINATE";

// Statistics
export const ABOUT_US_STATISTICS_PRIVILEGE = "ABOUT_US_STATISTICS";
export const ABOUT_US_STATISTICS_VIEW_PRIVILEGE = "ABOUT_US_STATISTICS_VIEW";
export const ABOUT_US_STATISTICS_DETAILS_VIEW_PRIVILEGE =
  "ABOUT_US_STATISTICS_DETAILS_VIEW";
export const ABOUT_US_STATISTICS_ADD_PRIVILEGE = "ABOUT_US_STATISTICS_ADD";
export const ABOUT_US_STATISTICS_UPDATE_PRIVILEGE =
  "ABOUT_US_STATISTICS_UPDATE";
export const ABOUT_US_STATISTICS_TERMINATE_PRIVILEGE =
  "ABOUT_US_STATISTICS_TERMINATE";

// Employee Social Media
export const ABOUT_US_EMPLOYEE_SOCIAL_MEDIA_PRIVILEGE =
  "ABOUT_US_EMPLOYEE_SOCIAL_MEDIA";
export const ABOUT_US_EMPLOYEE_SOCIAL_MEDIA_VIEW_PRIVILEGE =
  "ABOUT_US_EMPLOYEE_SOCIAL_MEDIA_VIEW";
export const ABOUT_US_EMPLOYEE_SOCIAL_MEDIA_DETAILS_VIEW_PRIVILEGE =
  "ABOUT_US_EMPLOYEE_SOCIAL_MEDIA_DETAILS_VIEW";
export const ABOUT_US_EMPLOYEE_SOCIAL_MEDIA_ADD_PRIVILEGE =
  "ABOUT_US_EMPLOYEE_SOCIAL_MEDIA_ADD";
export const ABOUT_US_EMPLOYEE_SOCIAL_MEDIA_UPDATE_PRIVILEGE =
  "ABOUT_US_EMPLOYEE_SOCIAL_MEDIA_UPDATE";
export const ABOUT_US_EMPLOYEE_SOCIAL_MEDIA_TERMINATE_PRIVILEGE =
  "ABOUT_US_EMPLOYEE_SOCIAL_MEDIA_TERMINATE";

// Tour Guides
export const ABOUT_US_TOUR_GUIDES_PRIVILEGE = "ABOUT_US_TOUR_GUIDES";
export const ABOUT_US_TOUR_GUIDES_VIEW_PRIVILEGE = "ABOUT_US_TOUR_GUIDES_VIEW";
export const ABOUT_US_TOUR_GUIDES_DETAILS_VIEW_PRIVILEGE =
  "ABOUT_US_TOUR_GUIDES_DETAILS_VIEW";
export const ABOUT_US_TOUR_GUIDES_ADD_PRIVILEGE = "ABOUT_US_TOUR_GUIDES_ADD";
export const ABOUT_US_TOUR_GUIDES_UPDATE_PRIVILEGE =
  "ABOUT_US_TOUR_GUIDES_UPDATE";
export const ABOUT_US_TOUR_GUIDES_TERMINATE_PRIVILEGE =
  "ABOUT_US_TOUR_GUIDES_TERMINATE";

// Our Office
export const ABOUT_US_OUR_OFFICE_PRIVILEGE = "ABOUT_US_OUR_OFFICE";
export const ABOUT_US_OUR_OFFICE_VIEW_PRIVILEGE = "ABOUT_US_OUR_OFFICE_VIEW";
export const ABOUT_US_OUR_OFFICE_DETAILS_VIEW_PRIVILEGE =
  "ABOUT_US_OUR_OFFICE_DETAILS_VIEW";
export const ABOUT_US_OUR_OFFICE_ADD_PRIVILEGE = "ABOUT_US_OUR_OFFICE_ADD";
export const ABOUT_US_OUR_OFFICE_UPDATE_PRIVILEGE =
  "ABOUT_US_OUR_OFFICE_UPDATE";
export const ABOUT_US_OUR_OFFICE_TERMINATE_PRIVILEGE =
  "ABOUT_US_OUR_OFFICE_TERMINATE";

// Our Features
export const ABOUT_US_OUR_FEATURES_PRIVILEGE = "ABOUT_US_FEATURES";
export const ABOUT_US_OUR_FEATURES_VIEW_PRIVILEGE = "ABOUT_US_FEATURES_VIEW";
export const ABOUT_US_OUR_FEATURES_DETAILS_VIEW_PRIVILEGE =
  "ABOUT_US_FEATURES_DETAILS_VIEW";
export const ABOUT_US_OUR_FEATURES_ADD_PRIVILEGE = "ABOUT_US_FEATURES_ADD";
export const ABOUT_US_OUR_FEATURES_UPDATE_PRIVILEGE =
  "ABOUT_US_FEATURES_UPDATE";
export const ABOUT_US_OUR_FEATURES_TERMINATE_PRIVILEGE =
  "ABOUT_US_FEATURES_TERMINATE";

// Achievements
export const ABOUT_US_ACHIEVEMENTS_PRIVILEGE = "ABOUT_US_ACHIEVEMENTS";
export const ABOUT_US_ACHIEVEMENTS_VIEW_PRIVILEGE =
  "ABOUT_US_ACHIEVEMENTS_VIEW";
export const ABOUT_US_ACHIEVEMENTS_DETAILS_VIEW_PRIVILEGE =
  "ABOUT_US_ACHIEVEMENTS_DETAILS_VIEW";
export const ABOUT_US_ACHIEVEMENTS_ADD_PRIVILEGE = "ABOUT_US_ACHIEVEMENTS_ADD";
export const ABOUT_US_ACHIEVEMENTS_UPDATE_PRIVILEGE =
  "ABOUT_US_ACHIEVEMENTS_UPDATE";
export const ABOUT_US_ACHIEVEMENTS_TERMINATE_PRIVILEGE =
  "ABOUT_US_ACHIEVEMENTS_TERMINATE";

// =========================================================
// WEB PAGE MANAGEMENT - DESTINATIONS PAGE
// =========================================================
export const DESTINATIONS_PAGE_PRIVILEGE = "DESTINATIONS_PAGE";

// Hero Section
export const DESTINATIONS_HERO_SECTION_PRIVILEGE = "DESTINATIONS_HERO_SECTION";
export const DESTINATIONS_HERO_SECTION_VIEW_PRIVILEGE =
  "DESTINATIONS_HERO_SECTION_VIEW";
export const DESTINATIONS_HERO_SECTION_DETAILS_VIEW_PRIVILEGE =
  "DESTINATIONS_HERO_SECTION_DETAILS_VIEW";
export const DESTINATIONS_HERO_SECTION_ADD_PRIVILEGE =
  "DESTINATIONS_HERO_SECTION_ADD";
export const DESTINATIONS_HERO_SECTION_UPDATE_PRIVILEGE =
  "DESTINATIONS_HERO_SECTION_UPDATE";
export const DESTINATIONS_HERO_SECTION_TERMINATE_PRIVILEGE =
  "DESTINATIONS_HERO_SECTION_TERMINATE";

// Reviews Section
export const DESTINATIONS_REVIEWS_SECTION_PRIVILEGE =
  "DESTINATIONS_REVIEWS_SECTION";
export const DESTINATIONS_REVIEWS_SECTION_VIEW_PRIVILEGE =
  "DESTINATIONS_REVIEWS_SECTION_VIEW";
export const DESTINATIONS_REVIEWS_SECTION_DETAILS_VIEW_PRIVILEGE =
  "DESTINATIONS_REVIEWS_SECTION_DETAILS_VIEW";
export const DESTINATIONS_REVIEWS_SECTION_ADD_PRIVILEGE =
  "DESTINATIONS_REVIEWS_SECTION_ADD";
export const DESTINATIONS_REVIEWS_SECTION_UPDATE_PRIVILEGE =
  "DESTINATIONS_REVIEWS_SECTION_UPDATE";
export const DESTINATIONS_REVIEWS_SECTION_TERMINATE_PRIVILEGE =
  "DESTINATIONS_REVIEWS_SECTION_TERMINATE";

// Destination History
export const DESTINATIONS_HISTORY_PRIVILEGE = "DESTINATIONS_HISTORY";
export const DESTINATIONS_HISTORY_VIEW_PRIVILEGE = "DESTINATIONS_HISTORY_VIEW";
export const DESTINATIONS_HISTORY_DETAILS_VIEW_PRIVILEGE =
  "DESTINATIONS_HISTORY_DETAILS_VIEW";
export const DESTINATIONS_HISTORY_ADD_PRIVILEGE = "DESTINATIONS_HISTORY_ADD";
export const DESTINATIONS_HISTORY_UPDATE_PRIVILEGE =
  "DESTINATIONS_HISTORY_UPDATE";
export const DESTINATIONS_HISTORY_TERMINATE_PRIVILEGE =
  "DESTINATIONS_HISTORY_TERMINATE";

// Destination History Gallery
export const DESTINATIONS_HISTORY_GALLERY_PRIVILEGE =
  "DESTINATIONS_HISTORY_GALLERY";
export const DESTINATIONS_HISTORY_GALLERY_VIEW_PRIVILEGE =
  "DESTINATIONS_HISTORY_GALLERY_VIEW";
export const DESTINATIONS_HISTORY_GALLERY_DETAILS_VIEW_PRIVILEGE =
  "DESTINATIONS_HISTORY_GALLERY_DETAILS_VIEW";
export const DESTINATIONS_HISTORY_GALLERY_ADD_PRIVILEGE =
  "DESTINATIONS_HISTORY_GALLERY_ADD";
export const DESTINATIONS_HISTORY_GALLERY_UPDATE_PRIVILEGE =
  "DESTINATIONS_HISTORY_GALLERY_UPDATE";
export const DESTINATIONS_HISTORY_GALLERY_TERMINATE_PRIVILEGE =
  "DESTINATIONS_HISTORY_GALLERY_TERMINATE";

// =========================================================
// WEB PAGE MANAGEMENT - DESTINATION DETAILS PAGE
// =========================================================
export const DESTINATION_DETAILS_PAGE_PRIVILEGE = "DESTINATION_DETAILS_PAGE";

// Hero Section
export const DESTINATION_DETAILS_HERO_SECTION_PRIVILEGE =
  "DESTINATION_DETAILS_HERO_SECTION";
export const DESTINATION_DETAILS_HERO_SECTION_VIEW_PRIVILEGE =
  "DESTINATION_DETAILS_HERO_SECTION_VIEW";
export const DESTINATION_DETAILS_HERO_SECTION_DETAILS_VIEW_PRIVILEGE =
  "DESTINATION_DETAILS_HERO_SECTION_DETAILS_VIEW";
export const DESTINATION_DETAILS_HERO_SECTION_ADD_PRIVILEGE =
  "DESTINATION_DETAILS_HERO_SECTION_ADD";
export const DESTINATION_DETAILS_HERO_SECTION_UPDATE_PRIVILEGE =
  "DESTINATION_DETAILS_HERO_SECTION_UPDATE";
export const DESTINATION_DETAILS_HERO_SECTION_TERMINATE_PRIVILEGE =
  "DESTINATION_DETAILS_HERO_SECTION_TERMINATE";

// Destination History
export const DESTINATION_DETAILS_HISTORY_PRIVILEGE =
  "DESTINATION_DETAILS_HISTORY";
export const DESTINATION_DETAILS_HISTORY_VIEW_PRIVILEGE =
  "DESTINATION_DETAILS_HISTORY_VIEW";
export const DESTINATION_DETAILS_HISTORY_DETAILS_VIEW_PRIVILEGE =
  "DESTINATION_DETAILS_HISTORY_DETAILS_VIEW";
export const DESTINATION_DETAILS_HISTORY_ADD_PRIVILEGE =
  "DESTINATION_DETAILS_HISTORY_ADD";
export const DESTINATION_DETAILS_HISTORY_UPDATE_PRIVILEGE =
  "DESTINATION_DETAILS_HISTORY_UPDATE";
export const DESTINATION_DETAILS_HISTORY_TERMINATE_PRIVILEGE =
  "DESTINATION_DETAILS_HISTORY_TERMINATE";

// Reviews Section
export const DESTINATION_DETAILS_REVIEWS_SECTION_PRIVILEGE =
  "DESTINATION_DETAILS_REVIEWS_SECTION";
export const DESTINATION_DETAILS_REVIEWS_SECTION_VIEW_PRIVILEGE =
  "DESTINATION_DETAILS_REVIEWS_SECTION_VIEW";
export const DESTINATION_DETAILS_REVIEWS_SECTION_DETAILS_VIEW_PRIVILEGE =
  "DESTINATION_DETAILS_REVIEWS_SECTION_DETAILS_VIEW";
export const DESTINATION_DETAILS_REVIEWS_SECTION_ADD_PRIVILEGE =
  "DESTINATION_DETAILS_REVIEWS_SECTION_ADD";
export const DESTINATION_DETAILS_REVIEWS_SECTION_UPDATE_PRIVILEGE =
  "DESTINATION_DETAILS_REVIEWS_SECTION_UPDATE";
export const DESTINATION_DETAILS_REVIEWS_SECTION_TERMINATE_PRIVILEGE =
  "DESTINATION_DETAILS_REVIEWS_SECTION_TERMINATE";

// Destination History Gallery
export const DESTINATION_DETAILS_HISTORY_GALLERY_PRIVILEGE =
  "DESTINATION_DETAILS_HISTORY_GALLERY";
export const DESTINATION_DETAILS_HISTORY_GALLERY_VIEW_PRIVILEGE =
  "DESTINATION_DETAILS_HISTORY_GALLERY_VIEW";
export const DESTINATION_DETAILS_HISTORY_GALLERY_DETAILS_VIEW_PRIVILEGE =
  "DESTINATION_DETAILS_HISTORY_GALLERY_DETAILS_VIEW";
export const DESTINATION_DETAILS_HISTORY_GALLERY_ADD_PRIVILEGE =
  "DESTINATION_DETAILS_HISTORY_GALLERY_ADD";
export const DESTINATION_DETAILS_HISTORY_GALLERY_UPDATE_PRIVILEGE =
  "DESTINATION_DETAILS_HISTORY_GALLERY_UPDATE";
export const DESTINATION_DETAILS_HISTORY_GALLERY_TERMINATE_PRIVILEGE =
  "DESTINATION_DETAILS_HISTORY_GALLERY_TERMINATE";

// =========================================================
// WEB PAGE MANAGEMENT - FAQ PAGE
// =========================================================
export const FAQ_PAGE_PRIVILEGE = "FAQ_PAGE";

// Hero Section
export const FAQ_HERO_SECTION_PRIVILEGE = "FAQ_HERO_SECTION";
export const FAQ_HERO_SECTION_VIEW_PRIVILEGE = "FAQ_HERO_SECTION_VIEW";
export const FAQ_HERO_SECTION_DETAILS_VIEW_PRIVILEGE =
  "FAQ_HERO_SECTION_DETAILS_VIEW";
export const FAQ_HERO_SECTION_ADD_PRIVILEGE = "FAQ_HERO_SECTION_ADD";
export const FAQ_HERO_SECTION_UPDATE_PRIVILEGE = "FAQ_HERO_SECTION_UPDATE";
export const FAQ_HERO_SECTION_TERMINATE_PRIVILEGE =
  "FAQ_HERO_SECTION_TERMINATE";

// Questions and Answers
export const FAQ_QUESTIONS_ANSWERS_PRIVILEGE = "FAQ_QUESTIONS_ANSWERS";
export const FAQ_QUESTIONS_ANSWERS_VIEW_PRIVILEGE =
  "FAQ_QUESTIONS_ANSWERS_VIEW";
export const FAQ_QUESTIONS_ANSWERS_DETAILS_VIEW_PRIVILEGE =
  "FAQ_QUESTIONS_ANSWERS_DETAILS_VIEW";
export const FAQ_QUESTIONS_ANSWERS_ADD_PRIVILEGE = "FAQ_QUESTIONS_ANSWERS_ADD";
export const FAQ_QUESTIONS_ANSWERS_UPDATE_PRIVILEGE =
  "FAQ_QUESTIONS_ANSWERS_UPDATE";
export const FAQ_QUESTIONS_ANSWERS_TERMINATE_PRIVILEGE =
  "FAQ_QUESTIONS_ANSWERS_TERMINATE";

// =========================================================
// WEB PAGE MANAGEMENT - CONTACT US PAGE
// =========================================================
export const CONTACT_US_PAGE_PRIVILEGE = "CONTACT_US_PAGE";

// Hero Section
export const CONTACT_US_HERO_SECTION_PRIVILEGE = "CONTACT_US_HERO_SECTION";
export const CONTACT_US_HERO_SECTION_VIEW_PRIVILEGE =
  "CONTACT_US_HERO_SECTION_VIEW";
export const CONTACT_US_HERO_SECTION_DETAILS_VIEW_PRIVILEGE =
  "CONTACT_US_HERO_SECTION_DETAILS_VIEW";
export const CONTACT_US_HERO_SECTION_ADD_PRIVILEGE =
  "CONTACT_US_HERO_SECTION_ADD";
export const CONTACT_US_HERO_SECTION_UPDATE_PRIVILEGE =
  "CONTACT_US_HERO_SECTION_UPDATE";
export const CONTACT_US_HERO_SECTION_TERMINATE_PRIVILEGE =
  "CONTACT_US_HERO_SECTION_TERMINATE";

// Contact Highlights
export const CONTACT_HIGHLIGHTS_PRIVILEGE = "CONTACT_HIGHLIGHTS";
export const CONTACT_HIGHLIGHTS_VIEW_PRIVILEGE = "CONTACT_HIGHLIGHTS_VIEW";
export const CONTACT_HIGHLIGHTS_DETAILS_VIEW_PRIVILEGE =
  "CONTACT_HIGHLIGHTS_DETAILS_VIEW";
export const CONTACT_HIGHLIGHTS_ADD_PRIVILEGE = "CONTACT_HIGHLIGHTS_ADD";
export const CONTACT_HIGHLIGHTS_UPDATE_PRIVILEGE = "CONTACT_HIGHLIGHTS_UPDATE";
export const CONTACT_HIGHLIGHTS_TERMINATE_PRIVILEGE =
  "CONTACT_HIGHLIGHTS_TERMINATE";

// Contact Form
export const CONTACT_FORM_PRIVILEGE = "CONTACT_FORM";
export const CONTACT_FORM_VIEW_PRIVILEGE = "CONTACT_FORM_VIEW";
export const CONTACT_FORM_DETAILS_VIEW_PRIVILEGE = "CONTACT_FORM_DETAILS_VIEW";
export const CONTACT_FORM_ADD_PRIVILEGE = "CONTACT_FORM_ADD";
export const CONTACT_FORM_UPDATE_PRIVILEGE = "CONTACT_FORM_UPDATE";
export const CONTACT_FORM_TERMINATE_PRIVILEGE = "CONTACT_FORM_TERMINATE";

// Call To Action
export const CONTACT_CALL_TO_ACTION_PRIVILEGE = "CONTACT_CALL_TO_ACTION";
export const CONTACT_CALL_TO_ACTION_VIEW_PRIVILEGE =
  "CONTACT_CALL_TO_ACTION_VIEW";
export const CONTACT_CALL_TO_ACTION_DETAILS_VIEW_PRIVILEGE =
  "CONTACT_CALL_TO_ACTION_DETAILS_VIEW";
export const CONTACT_CALL_TO_ACTION_ADD_PRIVILEGE =
  "CONTACT_CALL_TO_ACTION_ADD";
export const CONTACT_CALL_TO_ACTION_UPDATE_PRIVILEGE =
  "CONTACT_CALL_TO_ACTION_UPDATE";
export const CONTACT_CALL_TO_ACTION_TERMINATE_PRIVILEGE =
  "CONTACT_CALL_TO_ACTION_TERMINATE";

// Contact Us Office
export const CONTACT_US_OFFICE_PRIVILEGE = "CONTACT_US_OFFICE";
export const CONTACT_US_OFFICE_VIEW_PRIVILEGE = "CONTACT_US_OFFICE_VIEW";
export const CONTACT_US_OFFICE_DETAILS_VIEW_PRIVILEGE =
  "CONTACT_US_OFFICE_DETAILS_VIEW";
export const CONTACT_US_OFFICE_ADD_PRIVILEGE = "CONTACT_US_OFFICE_ADD";
export const CONTACT_US_OFFICE_UPDATE_PRIVILEGE = "CONTACT_US_OFFICE_UPDATE";
export const CONTACT_US_OFFICE_TERMINATE_PRIVILEGE =
  "CONTACT_US_OFFICE_TERMINATE";

// Business Information
export const BUSINESS_INFORMATION_PRIVILEGE = "BUSINESS_INFORMATION";
export const BUSINESS_INFORMATION_VIEW_PRIVILEGE = "BUSINESS_INFORMATION_VIEW";
export const BUSINESS_INFORMATION_DETAILS_VIEW_PRIVILEGE =
  "BUSINESS_INFORMATION_DETAILS_VIEW";
export const BUSINESS_INFORMATION_ADD_PRIVILEGE = "BUSINESS_INFORMATION_ADD";
export const BUSINESS_INFORMATION_UPDATE_PRIVILEGE =
  "BUSINESS_INFORMATION_UPDATE";
export const BUSINESS_INFORMATION_TERMINATE_PRIVILEGE =
  "BUSINESS_INFORMATION_TERMINATE";

// Contact Us Social Media
export const CONTACT_US_SOCIAL_MEDIA_PRIVILEGE = "CONTACT_US_SOCIAL_MEDIA";
export const CONTACT_US_SOCIAL_MEDIA_VIEW_PRIVILEGE =
  "CONTACT_US_SOCIAL_MEDIA_VIEW";
export const CONTACT_US_SOCIAL_MEDIA_DETAILS_VIEW_PRIVILEGE =
  "CONTACT_US_SOCIAL_MEDIA_DETAILS_VIEW";
export const CONTACT_US_SOCIAL_MEDIA_ADD_PRIVILEGE =
  "CONTACT_US_SOCIAL_MEDIA_ADD";
export const CONTACT_US_SOCIAL_MEDIA_UPDATE_PRIVILEGE =
  "CONTACT_US_SOCIAL_MEDIA_UPDATE";
export const CONTACT_US_SOCIAL_MEDIA_TERMINATE_PRIVILEGE =
  "CONTACT_US_SOCIAL_MEDIA_TERMINATE";

// =========================================================
// EMPLOYEE MANAGEMENT
// =========================================================
export const EMPLOYEE_PAGE_MANAGEMENT_PRIVILEGE = "EMPLOYEE_MANAGEMENT";
export const EMPLOYEE_VIEW_PRIVILEGE = "EMPLOYEE_VIEW";
export const EMPLOYEE_DETAILS_VIEW_PRIVILEGE = "EMPLOYEE_VIEW";
export const EMPLOYEE_CREATE_PRIVILEGE = "EMPLOYEE_CREATE";
export const EMPLOYEE_UPDATE_PRIVILEGE = "EMPLOYEE_UPDATE";
export const EMPLOYEE_RESIGN_PRIVILEGE = "EMPLOYEE_RESIGN";
export const EMPLOYEE_TERMINATE_PRIVILEGE = "EMPLOYEE_TERMINATE";

// =========================================================
// ROLE MANAGEMENT
// =========================================================
export const ROLE_MANAGEMENT_PRIVILEGE = "ROLE_MANAGEMENT";
export const ROLE_VIEW_PRIVILEGE = "ROLE_VIEW";
export const ROLE_DETAILS_VIEW_PRIVILEGE = "ROLE_VIEW";
export const ROLE_CREATE_PRIVILEGE = "ROLE_CREATE";
export const ROLE_UPDATE_PRIVILEGE = "ROLE_UPDATE";
export const ROLE_TERMINATE_PRIVILEGE = "ROLE_TERMINATE";

// =========================================================
// PRIVILEGE MANAGEMENT
// =========================================================
export const PRIVILEGE_MANAGEMENT_PRIVILEGE = "PRIVILEGE_MANAGEMENT";
export const PRIVILEGE_VIEW_PRIVILEGE = "PRIVILEGE_VIEW";
export const PRIVILEGE_DETAILS_VIEW_PRIVILEGE = "PRIVILEGE_VIEW";
export const PRIVILEGE_CREATE_PRIVILEGE = "PRIVILEGE_CREATE";
export const PRIVILEGE_UPDATE_PRIVILEGE = "PRIVILEGE_UPDATE";
export const PRIVILEGE_TERMINATE_PRIVILEGE = "PRIVILEGE_TERMINATE";

// =========================================================
// HOTEL MANAGEMENT
// =========================================================
export const HOTEL_PRIVILEGE = "HOTEL";
export const HOTEL_VIEW_PRIVILEGE = "HOTEL_VIEW";
export const HOTEL_CREATE_PRIVILEGE = "HOTEL_CREATE";
export const HOTEL_UPDATE_PRIVILEGE = "HOTEL_UPDATE";
export const HOTEL_TERMINATE_PRIVILEGE = "HOTEL_TERMINATE";

// =========================================================
// VEHICLE MANAGEMENT
// =========================================================
export const VEHICLE_PRIVILEGE = "VEHICLE";
export const VEHICLE_VIEW_PRIVILEGE = "VEHICLE_VIEW";
export const VEHICLE_CREATE_PRIVILEGE = "VEHICLE_CREATE";
export const VEHICLE_UPDATE_PRIVILEGE = "VEHICLE_UPDATE";
export const VEHICLE_TERMINATE_PRIVILEGE = "VEHICLE_TERMINATE";
