export const WEB_MANAGEMENT_URL = "/web-management";
export const TRAVEL_MANAGEMENT_URL = "/travel-management";
export const EMPLOYEE_MANAGEMENT_URL = "/employee-management";
export const HOTEL_MANAGEMENT_URL = "/hotel-management";
export const VEHICLE_MANAGEMENT_URL = "/vehicle-management";
export const ERP_SYSTEM_URL = "/erp-system";

export const DESTINATION_PAGE_URL = `${WEB_MANAGEMENT_URL}/destinations`;
export const DESTINATIONS_VIEW_PAGE_URL = `${DESTINATION_PAGE_URL}/view`;
export const DESTINATION_DETAILS_VIEW_PAGE_URL = `${DESTINATIONS_VIEW_PAGE_URL}`;
export const DESTINATION_UPDATE_PAGE_URL = `${DESTINATION_PAGE_URL}/update`;
export const DESTINATION_TERMINATE_PAGE_URL = `${DESTINATION_PAGE_URL}/terminate`;

export const DESTINATION_CATEGORIES_PAGE_URL = `${DESTINATION_PAGE_URL}/categories`;
export const DESTINATION_CATEGORY_VIEW_PAGE_URL = `${DESTINATION_CATEGORIES_PAGE_URL}/view`;
export const DESTINATION_CATEGORY_VIEW_DETAILS_URL = `${DESTINATION_CATEGORY_VIEW_PAGE_URL}`;

export const ACTIVITIES_PAGE_URL = `${WEB_MANAGEMENT_URL}/activities`;
export const ACTIVITIES_VIEW_PAGE_URL = `${ACTIVITIES_PAGE_URL}/view`;
export const ACTIVITY_DETAILS_VIEW_PAGE_URL = `${ACTIVITIES_VIEW_PAGE_URL}`;

export const ACTIVITY_CATEGORIES_PAGE_URL = `${ACTIVITIES_PAGE_URL}/categories`;
export const ACTIVITY_CATEGORY_VIEW_PAGE_URL = `${ACTIVITY_CATEGORIES_PAGE_URL}/view`;
export const ACTIVITY_CATEGORY_VIEW_DETAILS_URL = `${ACTIVITY_CATEGORY_VIEW_PAGE_URL}`;


export const SEASONS_PAGE_URL = `${WEB_MANAGEMENT_URL}/seasons`;
export const SEASONS_VIEW_PAGE_URL = `${SEASONS_PAGE_URL}/view`;
export const SEASON_DETAILS_VIEW_PAGE_URL = `${SEASONS_VIEW_PAGE_URL}`;