// Base URLs
export const HOME_PAGE_URL = "/";
export const LOGIN_PAGE_URL = "/login";
export const LOGOUT_PAGE_URL = "/logout";
export const SIGNUP_PAGE_URL = "/signup";
export const PROFILE_PAGE_URL = "/profile";
export const SETTINGS_PAGE_URL = "/settings";
export const UNAUTHORIZED_PAGE_URL = "/unauthorized";

export const CONTENT_MANAGEMENT_URL = "/content-management";
export const BOOKING_MANAGEMENT_URL = "/booking-management";
export const WEBSITE_CONTENT_MANAGEMENT_URL = "/website-content-management";

export const EMPLOYEE_MANAGEMENT_URL = "/employee-management";
export const HOTEL_MANAGEMENT_URL = "/hotel-management";
export const VEHICLE_MANAGEMENT_URL = "/vehicle-management";
export const ERP_SYSTEM_URL = "/erp-system";

// ==================== DESTINATIONS ====================
export const DESTINATION_PAGE_URL = `${CONTENT_MANAGEMENT_URL}/destinations`;
export const DESTINATION_VIEW_PAGE_URL = `${DESTINATION_PAGE_URL}/view`;
export const DESTINATION_DETAILS_VIEW_PAGE_URL = `${DESTINATION_VIEW_PAGE_URL}`;
export const DESTINATION_ADD_PAGE_URL = `${DESTINATION_PAGE_URL}/add-new`;
export const DESTINATION_UPDATE_PAGE_URL = `${DESTINATION_PAGE_URL}/update`;
export const DESTINATION_TERMINATE_PAGE_URL = `${DESTINATION_PAGE_URL}/terminate`;

// Destination Categories
export const DESTINATION_CATEGORIES_PAGE_URL = `${DESTINATION_PAGE_URL}/categories`;
export const DESTINATION_CATEGORY_VIEW_PAGE_URL = `${DESTINATION_CATEGORIES_PAGE_URL}/view`;
export const DESTINATION_CATEGORY_DETAILS_VIEW_URL = `${DESTINATION_CATEGORY_VIEW_PAGE_URL}/details`;
export const DESTINATION_CATEGORY_ADD_URL = `${DESTINATION_CATEGORIES_PAGE_URL}/add-new`;
export const DESTINATION_CATEGORY_UPDATE_URL = `${DESTINATION_CATEGORIES_PAGE_URL}/update`;
export const DESTINATION_CATEGORY_TERMINATE_URL = `${DESTINATION_CATEGORIES_PAGE_URL}/terminate`;

// ==================== ACTIVITIES ====================
export const ACTIVITIES_PAGE_URL = `${CONTENT_MANAGEMENT_URL}/activities`;
export const ACTIVITIES_VIEW_PAGE_URL = `${ACTIVITIES_PAGE_URL}/view`;
export const ACTIVITY_DETAILS_VIEW_PAGE_URL = `${ACTIVITIES_VIEW_PAGE_URL}/details`;
export const ACTIVITY_ADD_PAGE_URL = `${ACTIVITIES_PAGE_URL}/add`;
export const ACTIVITY_UPDATE_PAGE_URL = `${ACTIVITIES_PAGE_URL}/update`;
export const ACTIVITY_TERMINATE_PAGE_URL = `${ACTIVITIES_PAGE_URL}/terminate`;

// Activity Categories
export const ACTIVITY_CATEGORIES_PAGE_URL = `${ACTIVITIES_PAGE_URL}/categories`;
export const ACTIVITY_CATEGORY_VIEW_PAGE_URL = `${ACTIVITY_CATEGORIES_PAGE_URL}/view`;
export const ACTIVITY_CATEGORY_DETAILS_VIEW_URL = `${ACTIVITY_CATEGORY_VIEW_PAGE_URL}/details`;
export const ACTIVITY_CATEGORY_ADD_URL = `${ACTIVITY_CATEGORIES_PAGE_URL}/add`;
export const ACTIVITY_CATEGORY_UPDATE_URL = `${ACTIVITY_CATEGORIES_PAGE_URL}/update`;
export const ACTIVITY_CATEGORY_TERMINATE_URL = `${ACTIVITY_CATEGORIES_PAGE_URL}/terminate`;

// ==================== TOURS ====================
export const TOURS_PAGE_URL = `${CONTENT_MANAGEMENT_URL}/tours`;
export const TOURS_VIEW_PAGE_URL = `${TOURS_PAGE_URL}/view`;
export const TOUR_DETAILS_VIEW_PAGE_URL = `${TOURS_VIEW_PAGE_URL}/details`;
export const TOUR_ADD_PAGE_URL = `${TOURS_PAGE_URL}/add`;
export const TOUR_UPDATE_PAGE_URL = `${TOURS_PAGE_URL}/update`;
export const TOUR_TERMINATE_PAGE_URL = `${TOURS_PAGE_URL}/terminate`;

// Tour Categories
export const TOUR_CATEGORIES_PAGE_URL = `${TOURS_PAGE_URL}/categories`;
export const TOUR_CATEGORY_VIEW_PAGE_URL = `${TOUR_CATEGORIES_PAGE_URL}/view`;
export const TOUR_CATEGORY_DETAILS_VIEW_URL = `${TOUR_CATEGORY_VIEW_PAGE_URL}/details`;
export const TOUR_CATEGORY_ADD_URL = `${TOUR_CATEGORIES_PAGE_URL}/add`;
export const TOUR_CATEGORY_UPDATE_URL = `${TOUR_CATEGORIES_PAGE_URL}/update`;
export const TOUR_CATEGORY_TERMINATE_URL = `${TOUR_CATEGORIES_PAGE_URL}/terminate`;

// Tour Types
export const TOUR_TYPES_PAGE_URL = `${TOURS_PAGE_URL}/types`;
export const TOUR_TYPE_VIEW_PAGE_URL = `${TOUR_TYPES_PAGE_URL}/view`;
export const TOUR_TYPE_DETAILS_VIEW_URL = `${TOUR_TYPE_VIEW_PAGE_URL}/details`;
export const TOUR_TYPE_ADD_URL = `${TOUR_TYPES_PAGE_URL}/add`;
export const TOUR_TYPE_UPDATE_URL = `${TOUR_TYPES_PAGE_URL}/update`;
export const TOUR_TYPE_TERMINATE_URL = `${TOUR_TYPES_PAGE_URL}/terminate`;

// ==================== PACKAGES ====================
export const PACKAGES_PAGE_URL = `${CONTENT_MANAGEMENT_URL}/packages`;
export const PACKAGES_VIEW_PAGE_URL = `${PACKAGES_PAGE_URL}/view`;
export const PACKAGE_DETAILS_VIEW_PAGE_URL = `${PACKAGES_VIEW_PAGE_URL}/details`;
export const PACKAGE_ADD_PAGE_URL = `${PACKAGES_PAGE_URL}/add`;
export const PACKAGE_UPDATE_PAGE_URL = `${PACKAGES_PAGE_URL}/update`;
export const PACKAGE_TERMINATE_PAGE_URL = `${PACKAGES_PAGE_URL}/terminate`;

// Package Types
export const PACKAGE_TYPES_PAGE_URL = `${PACKAGES_PAGE_URL}/types`;
export const PACKAGE_TYPE_VIEW_PAGE_URL = `${PACKAGE_TYPES_PAGE_URL}/view`;
export const PACKAGE_TYPE_DETAILS_VIEW_URL = `${PACKAGE_TYPE_VIEW_PAGE_URL}/details`;
export const PACKAGE_TYPE_ADD_URL = `${PACKAGE_TYPES_PAGE_URL}/add`;
export const PACKAGE_TYPE_UPDATE_URL = `${PACKAGE_TYPES_PAGE_URL}/update`;
export const PACKAGE_TYPE_TERMINATE_URL = `${PACKAGE_TYPES_PAGE_URL}/terminate`;

// ==================== SCHEDULES ====================
// Activity Schedule
export const ACTIVITY_SCHEDULE_PAGE_URL = `${CONTENT_MANAGEMENT_URL}/activity-schedules`;
export const ACTIVITY_SCHEDULE_VIEW_PAGE_URL = `${ACTIVITY_SCHEDULE_PAGE_URL}/view`;
export const ACTIVITY_SCHEDULE_DETAILS_VIEW_URL = `${ACTIVITY_SCHEDULE_VIEW_PAGE_URL}/details`;
export const ACTIVITY_SCHEDULE_ADD_URL = `${ACTIVITY_SCHEDULE_PAGE_URL}/add`;
export const ACTIVITY_SCHEDULE_UPDATE_URL = `${ACTIVITY_SCHEDULE_PAGE_URL}/update`;
export const ACTIVITY_SCHEDULE_TERMINATE_URL = `${ACTIVITY_SCHEDULE_PAGE_URL}/terminate`;

// Tour Schedule
export const TOUR_SCHEDULE_PAGE_URL = `${CONTENT_MANAGEMENT_URL}/tour-schedules`;
export const TOUR_SCHEDULE_VIEW_PAGE_URL = `${TOUR_SCHEDULE_PAGE_URL}/view`;
export const TOUR_SCHEDULE_DETAILS_VIEW_URL = `${TOUR_SCHEDULE_VIEW_PAGE_URL}/details`;
export const TOUR_SCHEDULE_ADD_URL = `${TOUR_SCHEDULE_PAGE_URL}/add`;
export const TOUR_SCHEDULE_UPDATE_URL = `${TOUR_SCHEDULE_PAGE_URL}/update`;
export const TOUR_SCHEDULE_TERMINATE_URL = `${TOUR_SCHEDULE_PAGE_URL}/terminate`;

// Package Schedule
export const PACKAGE_SCHEDULE_PAGE_URL = `${CONTENT_MANAGEMENT_URL}/package-schedules`;
export const PACKAGE_SCHEDULE_VIEW_PAGE_URL = `${PACKAGE_SCHEDULE_PAGE_URL}/view`;
export const PACKAGE_SCHEDULE_DETAILS_VIEW_URL = `${PACKAGE_SCHEDULE_VIEW_PAGE_URL}/details`;
export const PACKAGE_SCHEDULE_ADD_URL = `${PACKAGE_SCHEDULE_PAGE_URL}/add`;
export const PACKAGE_SCHEDULE_UPDATE_URL = `${PACKAGE_SCHEDULE_PAGE_URL}/update`;
export const PACKAGE_SCHEDULE_TERMINATE_URL = `${PACKAGE_SCHEDULE_PAGE_URL}/terminate`;

// Seasons
export const SEASONS_PAGE_URL = `${CONTENT_MANAGEMENT_URL}/seasons`;
export const SEASONS_VIEW_PAGE_URL = `${SEASONS_PAGE_URL}/view`;
export const SEASON_DETAILS_VIEW_PAGE_URL = `${SEASONS_VIEW_PAGE_URL}/details`;
export const SEASON_ADD_PAGE_URL = `${SEASONS_PAGE_URL}/add`;
export const SEASON_UPDATE_PAGE_URL = `${SEASONS_PAGE_URL}/update`;
export const SEASON_TERMINATE_PAGE_URL = `${SEASONS_PAGE_URL}/terminate`;

// ==================== BOOKING MANAGEMENT URLS ====================
// Tour Bookings
export const TOUR_BOOKINGS_PAGE_URL = `${BOOKING_MANAGEMENT_URL}/tour-bookings`;
export const TOUR_BOOKINGS_VIEW_PAGE_URL = `${TOUR_BOOKINGS_PAGE_URL}/view`;
export const TOUR_BOOKINGS_DETAILS_VIEW_URL = `${TOUR_BOOKINGS_VIEW_PAGE_URL}/details`;
export const TOUR_BOOKINGS_ADD_PAGE_URL = `${TOUR_BOOKINGS_PAGE_URL}/add`;
export const TOUR_BOOKINGS_UPDATE_PAGE_URL = `${TOUR_BOOKINGS_PAGE_URL}/update`;
export const TOUR_BOOKINGS_CANCEL_PAGE_URL = `${TOUR_BOOKINGS_PAGE_URL}/cancel`;

// ==================== EMPLOYEE MANAGEMENT ====================
// Privileges
export const PRIVILEGES_MANAGEMENT_PAGE_URL = `${EMPLOYEE_MANAGEMENT_URL}/privileges`;
export const PRIVILEGES_VIEW_PAGE_URL = `${PRIVILEGES_MANAGEMENT_PAGE_URL}/view`;
export const PRIVILEGES_DETAILS_VIEW_URL = `${PRIVILEGES_VIEW_PAGE_URL}/details`;
export const PRIVILEGES_ADD_PAGE_URL = `${PRIVILEGES_MANAGEMENT_PAGE_URL}/add`;
export const PRIVILEGES_UPDATE_PAGE_URL = `${PRIVILEGES_MANAGEMENT_PAGE_URL}/update`;
export const PRIVILEGES_TERMINATE_PAGE_URL = `${PRIVILEGES_MANAGEMENT_PAGE_URL}/terminate`;

// Roles
export const ROLES_MANAGEMENT_PAGE_URL = `${EMPLOYEE_MANAGEMENT_URL}/roles`;
export const ROLES_VIEW_PAGE_URL = `${ROLES_MANAGEMENT_PAGE_URL}/view`;
export const ROLES_DETAILS_VIEW_URL = `${ROLES_VIEW_PAGE_URL}/details`;
export const ROLES_ADD_PAGE_URL = `${ROLES_MANAGEMENT_PAGE_URL}/add`;
export const ROLES_UPDATE_PAGE_URL = `${ROLES_MANAGEMENT_PAGE_URL}/update`;
export const ROLES_TERMINATE_PAGE_URL = `${ROLES_MANAGEMENT_PAGE_URL}/terminate`;

// Employees
export const EMPLOYEES_MANAGEMENT_PAGE_URL = `${EMPLOYEE_MANAGEMENT_URL}/employees`;
export const EMPLOYEES_VIEW_PAGE_URL = `${EMPLOYEES_MANAGEMENT_PAGE_URL}/view`;
export const EMPLOYEES_DETAILS_VIEW_PAGE_URL = `${EMPLOYEES_VIEW_PAGE_URL}/details`;
export const EMPLOYEE_ADD_PAGE_URL = `${EMPLOYEES_MANAGEMENT_PAGE_URL}/add`;
export const EMPLOYEE_UPDATE_PAGE_URL = `${EMPLOYEES_MANAGEMENT_PAGE_URL}/update`;
export const EMPLOYEE_TERMINATE_PAGE_URL = `${EMPLOYEES_MANAGEMENT_PAGE_URL}/terminate`;

// ==================== WEB PAGE MANAGEMENT ====================
// Home Page
export const WEB_HOME_PAGE_URL = `${WEBSITE_CONTENT_MANAGEMENT_URL}/home-page`;

// Hero Section
export const HOME_HERO_SECTION_URL = `${WEB_HOME_PAGE_URL}/hero-section`;
export const HOME_HERO_SECTION_VIEW_URL = `${HOME_HERO_SECTION_URL}/view`;
export const HOME_HERO_SECTION_DETAILS_VIEW_URL = `${HOME_HERO_SECTION_VIEW_URL}/details`;
export const HOME_HERO_SECTION_ADD_URL = `${HOME_HERO_SECTION_URL}/add`;
export const HOME_HERO_SECTION_UPDATE_URL = `${HOME_HERO_SECTION_URL}/update`;
export const HOME_HERO_SECTION_TERMINATE_URL = `${HOME_HERO_SECTION_URL}/terminate`;

// Why Choose Us
export const HOME_WHY_CHOOSE_US_URL = `${WEB_HOME_PAGE_URL}/why-choose-us`;
export const HOME_WHY_CHOOSE_US_VIEW_URL = `${HOME_WHY_CHOOSE_US_URL}/view`;
export const HOME_WHY_CHOOSE_US_DETAILS_VIEW_URL = `${HOME_WHY_CHOOSE_US_VIEW_URL}/details`;
export const HOME_WHY_CHOOSE_US_ADD_URL = `${HOME_WHY_CHOOSE_US_URL}/add`;
export const HOME_WHY_CHOOSE_US_UPDATE_URL = `${HOME_WHY_CHOOSE_US_URL}/update`;
export const HOME_WHY_CHOOSE_US_TERMINATE_URL = `${HOME_WHY_CHOOSE_US_URL}/terminate`;

// Our Services
export const HOME_OUR_SERVICES_URL = `${WEB_HOME_PAGE_URL}/our-services`;
export const HOME_OUR_SERVICES_VIEW_URL = `${HOME_OUR_SERVICES_URL}/view`;
export const HOME_OUR_SERVICES_DETAILS_VIEW_URL = `${HOME_OUR_SERVICES_VIEW_URL}/details`;
export const HOME_OUR_SERVICES_ADD_URL = `${HOME_OUR_SERVICES_URL}/add`;
export const HOME_OUR_SERVICES_UPDATE_URL = `${HOME_OUR_SERVICES_URL}/update`;
export const HOME_OUR_SERVICES_TERMINATE_URL = `${HOME_OUR_SERVICES_URL}/terminate`;

// Trending Destinations
export const HOME_TRENDING_DESTINATIONS_URL = `${WEB_HOME_PAGE_URL}/trending-destinations`;
export const HOME_TRENDING_DESTINATIONS_VIEW_URL = `${HOME_TRENDING_DESTINATIONS_URL}/view`;
export const HOME_TRENDING_DESTINATIONS_DETAILS_VIEW_URL = `${HOME_TRENDING_DESTINATIONS_VIEW_URL}/details`;
export const HOME_TRENDING_DESTINATIONS_ADD_URL = `${HOME_TRENDING_DESTINATIONS_URL}/add`;
export const HOME_TRENDING_DESTINATIONS_UPDATE_URL = `${HOME_TRENDING_DESTINATIONS_URL}/update`;
export const HOME_TRENDING_DESTINATIONS_TERMINATE_URL = `${HOME_TRENDING_DESTINATIONS_URL}/terminate`;

// Active Tours
export const HOME_ACTIVE_TOURS_URL = `${WEB_HOME_PAGE_URL}/active-tours`;
export const HOME_ACTIVE_TOURS_VIEW_URL = `${HOME_ACTIVE_TOURS_URL}/view`;
export const HOME_ACTIVE_TOURS_DETAILS_VIEW_URL = `${HOME_ACTIVE_TOURS_VIEW_URL}/details`;
export const HOME_ACTIVE_TOURS_ADD_URL = `${HOME_ACTIVE_TOURS_URL}/add`;
export const HOME_ACTIVE_TOURS_UPDATE_URL = `${HOME_ACTIVE_TOURS_URL}/update`;
export const HOME_ACTIVE_TOURS_TERMINATE_URL = `${HOME_ACTIVE_TOURS_URL}/terminate`;

// Tour Map
export const HOME_TOUR_MAP_URL = `${WEB_HOME_PAGE_URL}/tour-map`;
export const HOME_TOUR_MAP_VIEW_URL = `${HOME_TOUR_MAP_URL}/view`;
export const HOME_TOUR_MAP_DETAILS_VIEW_URL = `${HOME_TOUR_MAP_VIEW_URL}/details`;
export const HOME_TOUR_MAP_ADD_URL = `${HOME_TOUR_MAP_URL}/add`;
export const HOME_TOUR_MAP_UPDATE_URL = `${HOME_TOUR_MAP_URL}/update`;
export const HOME_TOUR_MAP_TERMINATE_URL = `${HOME_TOUR_MAP_URL}/terminate`;

// Activity Categories
export const HOME_ACTIVITY_CATEGORIES_URL = `${WEB_HOME_PAGE_URL}/activity-categories`;
export const HOME_ACTIVITY_CATEGORIES_VIEW_URL = `${HOME_ACTIVITY_CATEGORIES_URL}/view`;
export const HOME_ACTIVITY_CATEGORIES_DETAILS_VIEW_URL = `${HOME_ACTIVITY_CATEGORIES_VIEW_URL}/details`;
export const HOME_ACTIVITY_CATEGORIES_ADD_URL = `${HOME_ACTIVITY_CATEGORIES_URL}/add`;
export const HOME_ACTIVITY_CATEGORIES_UPDATE_URL = `${HOME_ACTIVITY_CATEGORIES_URL}/update`;
export const HOME_ACTIVITY_CATEGORIES_TERMINATE_URL = `${HOME_ACTIVITY_CATEGORIES_URL}/terminate`;

// Gallery
export const HOME_GALLERY_URL = `${WEB_HOME_PAGE_URL}/gallery`;
export const HOME_GALLERY_VIEW_URL = `${HOME_GALLERY_URL}/view`;
export const HOME_GALLERY_DETAILS_VIEW_URL = `${HOME_GALLERY_VIEW_URL}/details`;
export const HOME_GALLERY_ADD_URL = `${HOME_GALLERY_URL}/add`;
export const HOME_GALLERY_UPDATE_URL = `${HOME_GALLERY_URL}/update`;
export const HOME_GALLERY_TERMINATE_URL = `${HOME_GALLERY_URL}/terminate`;

// Contact Form
export const HOME_CONTACT_FORM_URL = `${WEB_HOME_PAGE_URL}/contact-form`;
export const HOME_CONTACT_FORM_VIEW_URL = `${HOME_CONTACT_FORM_URL}/view`;
export const HOME_CONTACT_FORM_DETAILS_VIEW_URL = `${HOME_CONTACT_FORM_VIEW_URL}/details`;
export const HOME_CONTACT_FORM_ADD_URL = `${HOME_CONTACT_FORM_URL}/add`;
export const HOME_CONTACT_FORM_UPDATE_URL = `${HOME_CONTACT_FORM_URL}/update`;
export const HOME_CONTACT_FORM_TERMINATE_URL = `${HOME_CONTACT_FORM_URL}/terminate`;

// About Us Page
export const WEB_ABOUT_US_PAGE_URL = `${WEBSITE_CONTENT_MANAGEMENT_URL}/about-us-page`;

// Hero Section
export const ABOUT_US_HERO_SECTION_URL = `${WEB_ABOUT_US_PAGE_URL}/hero-section`;
export const ABOUT_US_HERO_SECTION_VIEW_URL = `${ABOUT_US_HERO_SECTION_URL}/view`;
export const ABOUT_US_HERO_SECTION_DETAILS_VIEW_URL = `${ABOUT_US_HERO_SECTION_VIEW_URL}/details`;
export const ABOUT_US_HERO_SECTION_ADD_URL = `${ABOUT_US_HERO_SECTION_URL}/add`;
export const ABOUT_US_HERO_SECTION_UPDATE_URL = `${ABOUT_US_HERO_SECTION_URL}/update`;
export const ABOUT_US_HERO_SECTION_TERMINATE_URL = `${ABOUT_US_HERO_SECTION_URL}/terminate`;

// Our Story
export const ABOUT_US_OUR_STORY_URL = `${WEB_ABOUT_US_PAGE_URL}/our-story`;
export const ABOUT_US_OUR_STORY_VIEW_URL = `${ABOUT_US_OUR_STORY_URL}/view`;
export const ABOUT_US_OUR_STORY_DETAILS_VIEW_URL = `${ABOUT_US_OUR_STORY_VIEW_URL}/details`;
export const ABOUT_US_OUR_STORY_ADD_URL = `${ABOUT_US_OUR_STORY_URL}/add`;
export const ABOUT_US_OUR_STORY_UPDATE_URL = `${ABOUT_US_OUR_STORY_URL}/update`;
export const ABOUT_US_OUR_STORY_TERMINATE_URL = `${ABOUT_US_OUR_STORY_URL}/terminate`;

// CEO Speech
export const ABOUT_US_CEO_SPEECH_URL = `${WEB_ABOUT_US_PAGE_URL}/ceo-speech`;
export const ABOUT_US_CEO_SPEECH_VIEW_URL = `${ABOUT_US_CEO_SPEECH_URL}/view`;
export const ABOUT_US_CEO_SPEECH_DETAILS_VIEW_URL = `${ABOUT_US_CEO_SPEECH_VIEW_URL}/details`;
export const ABOUT_US_CEO_SPEECH_ADD_URL = `${ABOUT_US_CEO_SPEECH_URL}/add`;
export const ABOUT_US_CEO_SPEECH_UPDATE_URL = `${ABOUT_US_CEO_SPEECH_URL}/update`;
export const ABOUT_US_CEO_SPEECH_TERMINATE_URL = `${ABOUT_US_CEO_SPEECH_URL}/terminate`;

// Why Choose Us
export const ABOUT_US_WHY_CHOOSE_US_URL = `${WEB_ABOUT_US_PAGE_URL}/why-choose-us`;
export const ABOUT_US_WHY_CHOOSE_US_VIEW_URL = `${ABOUT_US_WHY_CHOOSE_US_URL}/view`;
export const ABOUT_US_WHY_CHOOSE_US_DETAILS_VIEW_URL = `${ABOUT_US_WHY_CHOOSE_US_VIEW_URL}/details`;
export const ABOUT_US_WHY_CHOOSE_US_ADD_URL = `${ABOUT_US_WHY_CHOOSE_US_URL}/add`;
export const ABOUT_US_WHY_CHOOSE_US_UPDATE_URL = `${ABOUT_US_WHY_CHOOSE_US_URL}/update`;
export const ABOUT_US_WHY_CHOOSE_US_TERMINATE_URL = `${ABOUT_US_WHY_CHOOSE_US_URL}/terminate`;

// Destinations Page
export const WEB_DESTINATIONS_PAGE_URL = `${WEBSITE_CONTENT_MANAGEMENT_URL}/destinations-page`;

// Hero Section
export const DESTINATIONS_HERO_SECTION_URL = `${WEB_DESTINATIONS_PAGE_URL}/hero-section`;
export const DESTINATIONS_HERO_SECTION_VIEW_URL = `${DESTINATIONS_HERO_SECTION_URL}/view`;
export const DESTINATIONS_HERO_SECTION_DETAILS_VIEW_URL = `${DESTINATIONS_HERO_SECTION_VIEW_URL}/details`;
export const DESTINATIONS_HERO_SECTION_ADD_URL = `${DESTINATIONS_HERO_SECTION_URL}/add`;
export const DESTINATIONS_HERO_SECTION_UPDATE_URL = `${DESTINATIONS_HERO_SECTION_URL}/update`;
export const DESTINATIONS_HERO_SECTION_TERMINATE_URL = `${DESTINATIONS_HERO_SECTION_URL}/terminate`;

// Reviews Section
export const DESTINATIONS_REVIEWS_SECTION_URL = `${WEB_DESTINATIONS_PAGE_URL}/reviews-section`;
export const DESTINATIONS_REVIEWS_SECTION_VIEW_URL = `${DESTINATIONS_REVIEWS_SECTION_URL}/view`;
export const DESTINATIONS_REVIEWS_SECTION_DETAILS_VIEW_URL = `${DESTINATIONS_REVIEWS_SECTION_VIEW_URL}/details`;
export const DESTINATIONS_REVIEWS_SECTION_ADD_URL = `${DESTINATIONS_REVIEWS_SECTION_URL}/add`;
export const DESTINATIONS_REVIEWS_SECTION_UPDATE_URL = `${DESTINATIONS_REVIEWS_SECTION_URL}/update`;
export const DESTINATIONS_REVIEWS_SECTION_TERMINATE_URL = `${DESTINATIONS_REVIEWS_SECTION_URL}/terminate`;

// Destination History
export const DESTINATIONS_HISTORY_URL = `${WEB_DESTINATIONS_PAGE_URL}/destination-history`;
export const DESTINATIONS_HISTORY_VIEW_URL = `${DESTINATIONS_HISTORY_URL}/view`;
export const DESTINATIONS_HISTORY_DETAILS_VIEW_URL = `${DESTINATIONS_HISTORY_VIEW_URL}/details`;
export const DESTINATIONS_HISTORY_ADD_URL = `${DESTINATIONS_HISTORY_URL}/add`;
export const DESTINATIONS_HISTORY_UPDATE_URL = `${DESTINATIONS_HISTORY_URL}/update`;
export const DESTINATIONS_HISTORY_TERMINATE_URL = `${DESTINATIONS_HISTORY_URL}/terminate`;

// Destination History Gallery
export const DESTINATIONS_HISTORY_GALLERY_URL = `${WEB_DESTINATIONS_PAGE_URL}/destination-history-gallery`;
export const DESTINATIONS_HISTORY_GALLERY_VIEW_URL = `${DESTINATIONS_HISTORY_GALLERY_URL}/view`;
export const DESTINATIONS_HISTORY_GALLERY_DETAILS_VIEW_URL = `${DESTINATIONS_HISTORY_GALLERY_VIEW_URL}/details`;
export const DESTINATIONS_HISTORY_GALLERY_ADD_URL = `${DESTINATIONS_HISTORY_GALLERY_URL}/add`;
export const DESTINATIONS_HISTORY_GALLERY_UPDATE_URL = `${DESTINATIONS_HISTORY_GALLERY_URL}/update`;
export const DESTINATIONS_HISTORY_GALLERY_TERMINATE_URL = `${DESTINATIONS_HISTORY_GALLERY_URL}/terminate`;

// Destination Details Page
export const WEB_DESTINATION_DETAILS_PAGE_URL = `${WEBSITE_CONTENT_MANAGEMENT_URL}/destination-details-page`;

// Hero Section
export const DESTINATION_DETAILS_HERO_SECTION_URL = `${WEB_DESTINATION_DETAILS_PAGE_URL}/hero-section`;
export const DESTINATION_DETAILS_HERO_SECTION_VIEW_URL = `${DESTINATION_DETAILS_HERO_SECTION_URL}/view`;
export const DESTINATION_DETAILS_HERO_SECTION_DETAILS_VIEW_URL = `${DESTINATION_DETAILS_HERO_SECTION_VIEW_URL}/details`;
export const DESTINATION_DETAILS_HERO_SECTION_ADD_URL = `${DESTINATION_DETAILS_HERO_SECTION_URL}/add`;
export const DESTINATION_DETAILS_HERO_SECTION_UPDATE_URL = `${DESTINATION_DETAILS_HERO_SECTION_URL}/update`;
export const DESTINATION_DETAILS_HERO_SECTION_TERMINATE_URL = `${DESTINATION_DETAILS_HERO_SECTION_URL}/terminate`;

// Destination History
export const DESTINATION_DETAILS_HISTORY_URL = `${WEB_DESTINATION_DETAILS_PAGE_URL}/destination-history`;
export const DESTINATION_DETAILS_HISTORY_VIEW_URL = `${DESTINATION_DETAILS_HISTORY_URL}/view`;
export const DESTINATION_DETAILS_HISTORY_DETAILS_VIEW_URL = `${DESTINATION_DETAILS_HISTORY_VIEW_URL}/details`;
export const DESTINATION_DETAILS_HISTORY_ADD_URL = `${DESTINATION_DETAILS_HISTORY_URL}/add`;
export const DESTINATION_DETAILS_HISTORY_UPDATE_URL = `${DESTINATION_DETAILS_HISTORY_URL}/update`;
export const DESTINATION_DETAILS_HISTORY_TERMINATE_URL = `${DESTINATION_DETAILS_HISTORY_URL}/terminate`;

// Reviews Section
export const DESTINATION_DETAILS_REVIEWS_SECTION_URL = `${WEB_DESTINATION_DETAILS_PAGE_URL}/reviews-section`;
export const DESTINATION_DETAILS_REVIEWS_SECTION_VIEW_URL = `${DESTINATION_DETAILS_REVIEWS_SECTION_URL}/view`;
export const DESTINATION_DETAILS_REVIEWS_SECTION_DETAILS_VIEW_URL = `${DESTINATION_DETAILS_REVIEWS_SECTION_VIEW_URL}/details`;
export const DESTINATION_DETAILS_REVIEWS_SECTION_ADD_URL = `${DESTINATION_DETAILS_REVIEWS_SECTION_URL}/add`;
export const DESTINATION_DETAILS_REVIEWS_SECTION_UPDATE_URL = `${DESTINATION_DETAILS_REVIEWS_SECTION_URL}/update`;
export const DESTINATION_DETAILS_REVIEWS_SECTION_TERMINATE_URL = `${DESTINATION_DETAILS_REVIEWS_SECTION_URL}/terminate`;

// History Gallery
export const DESTINATION_DETAILS_HISTORY_GALLERY_URL = `${WEB_DESTINATION_DETAILS_PAGE_URL}/destination-history-gallery`;
export const DESTINATION_DETAILS_HISTORY_GALLERY_VIEW_URL = `${DESTINATION_DETAILS_HISTORY_GALLERY_URL}/view`;
export const DESTINATION_DETAILS_HISTORY_GALLERY_DETAILS_VIEW_URL = `${DESTINATION_DETAILS_HISTORY_GALLERY_VIEW_URL}/details`;
export const DESTINATION_DETAILS_HISTORY_GALLERY_ADD_URL = `${DESTINATION_DETAILS_HISTORY_GALLERY_URL}/add`;
export const DESTINATION_DETAILS_HISTORY_GALLERY_UPDATE_URL = `${DESTINATION_DETAILS_HISTORY_GALLERY_URL}/update`;
export const DESTINATION_DETAILS_HISTORY_GALLERY_TERMINATE_URL = `${DESTINATION_DETAILS_HISTORY_GALLERY_URL}/terminate`;

// FAQ Page
export const WEB_FAQ_PAGE_URL = `${WEBSITE_CONTENT_MANAGEMENT_URL}/faq-page`;

// Hero Section
export const FAQ_HERO_SECTION_URL = `${WEB_FAQ_PAGE_URL}/hero-section`;
export const FAQ_HERO_SECTION_VIEW_URL = `${FAQ_HERO_SECTION_URL}/view`;
export const FAQ_HERO_SECTION_DETAILS_VIEW_URL = `${FAQ_HERO_SECTION_VIEW_URL}/details`;
export const FAQ_HERO_SECTION_ADD_URL = `${FAQ_HERO_SECTION_URL}/add`;
export const FAQ_HERO_SECTION_UPDATE_URL = `${FAQ_HERO_SECTION_URL}/update`;
export const FAQ_HERO_SECTION_TERMINATE_URL = `${FAQ_HERO_SECTION_URL}/terminate`;

// Questions and Answers
export const FAQ_QUESTIONS_ANSWERS_URL = `${WEB_FAQ_PAGE_URL}/questions-and-answers`;
export const FAQ_QUESTIONS_ANSWERS_VIEW_URL = `${FAQ_QUESTIONS_ANSWERS_URL}/view`;
export const FAQ_QUESTIONS_ANSWERS_DETAILS_VIEW_URL = `${FAQ_QUESTIONS_ANSWERS_VIEW_URL}/details`;
export const FAQ_QUESTIONS_ANSWERS_ADD_URL = `${FAQ_QUESTIONS_ANSWERS_URL}/add`;
export const FAQ_QUESTIONS_ANSWERS_UPDATE_URL = `${FAQ_QUESTIONS_ANSWERS_URL}/update`;
export const FAQ_QUESTIONS_ANSWERS_TERMINATE_URL = `${FAQ_QUESTIONS_ANSWERS_URL}/terminate`;

// Contact Us Page
export const WEB_CONTACT_US_PAGE_URL = `${WEBSITE_CONTENT_MANAGEMENT_URL}/contact-us-page`;

// Hero Section
export const CONTACT_US_HERO_SECTION_URL = `${WEB_CONTACT_US_PAGE_URL}/hero-section`;
export const CONTACT_US_HERO_SECTION_VIEW_URL = `${CONTACT_US_HERO_SECTION_URL}/view`;
export const CONTACT_US_HERO_SECTION_DETAILS_VIEW_URL = `${CONTACT_US_HERO_SECTION_VIEW_URL}/details`;
export const CONTACT_US_HERO_SECTION_ADD_URL = `${CONTACT_US_HERO_SECTION_URL}/add`;
export const CONTACT_US_HERO_SECTION_UPDATE_URL = `${CONTACT_US_HERO_SECTION_URL}/update`;
export const CONTACT_US_HERO_SECTION_TERMINATE_URL = `${CONTACT_US_HERO_SECTION_URL}/terminate`;

// Contact Highlights
export const CONTACT_HIGHLIGHTS_URL = `${WEB_CONTACT_US_PAGE_URL}/contact-highlights`;
export const CONTACT_HIGHLIGHTS_VIEW_URL = `${CONTACT_HIGHLIGHTS_URL}/view`;
export const CONTACT_HIGHLIGHTS_DETAILS_VIEW_URL = `${CONTACT_HIGHLIGHTS_VIEW_URL}/details`;
export const CONTACT_HIGHLIGHTS_ADD_URL = `${CONTACT_HIGHLIGHTS_URL}/add`;
export const CONTACT_HIGHLIGHTS_UPDATE_URL = `${CONTACT_HIGHLIGHTS_URL}/update`;
export const CONTACT_HIGHLIGHTS_TERMINATE_URL = `${CONTACT_HIGHLIGHTS_URL}/terminate`;

// Contact Form
export const CONTACT_FORM_URL = `${WEB_CONTACT_US_PAGE_URL}/contact-form`;
export const CONTACT_FORM_VIEW_URL = `${CONTACT_FORM_URL}/view`;
export const CONTACT_FORM_DETAILS_VIEW_URL = `${CONTACT_FORM_VIEW_URL}/details`;
export const CONTACT_FORM_ADD_URL = `${CONTACT_FORM_URL}/add`;
export const CONTACT_FORM_UPDATE_URL = `${CONTACT_FORM_URL}/update`;
export const CONTACT_FORM_TERMINATE_URL = `${CONTACT_FORM_URL}/terminate`;

// Call To Action
export const CONTACT_CALL_TO_ACTION_URL = `${WEB_CONTACT_US_PAGE_URL}/call-to-action`;
export const CONTACT_CALL_TO_ACTION_VIEW_URL = `${CONTACT_CALL_TO_ACTION_URL}/view`;
export const CONTACT_CALL_TO_ACTION_DETAILS_VIEW_URL = `${CONTACT_CALL_TO_ACTION_VIEW_URL}/details`;
export const CONTACT_CALL_TO_ACTION_ADD_URL = `${CONTACT_CALL_TO_ACTION_URL}/add`;
export const CONTACT_CALL_TO_ACTION_UPDATE_URL = `${CONTACT_CALL_TO_ACTION_URL}/update`;
export const CONTACT_CALL_TO_ACTION_TERMINATE_URL = `${CONTACT_CALL_TO_ACTION_URL}/terminate`;
